### ISSUE TITLE
Can we timestamp in metadata filename that is added after file is on server?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#101]
@n8fr8 it'd be great to be able to add a timestamp to any metadata that’s already on the server (such as notes/proofmode) 
Would it be different for Save metadata vs. Proofmode?

**Comment by johnhess** [comment]
@foundscapes I don't quite follow this one.  Can you clarify it for me with a walkthrough of who would do what and what changes that would cause?
