### ISSUE TITLE
Integrated Tor.framework for WebDAV/HTTP over Tor

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-ios#103]

**Comment by foundscapes** [comment]
@tladesignz is this possible to do before you leave?

**Comment by tladesignz** [comment]
@foundscapes No way.

**Comment by n8fr8** [comment]
Let's discuss the scope, possibilities of this again

**Comment by tladesignz** [comment]
Save now supports Orbot, which seems the better way to support Tor, as this way it doesn't make Save unavailable in China.

**Comment by n8fr8** [comment]
Great!
