### ISSUE TITLE
Go Directly to Project when choosing folder?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#115]
@tladesignz @kckthx @cstiens Is clicking "done" in upper right of choose your project screen redundant? Could it just be added by clicking on the project or does this introduce usability issues?

**Comment by kckthx** [comment]
Assuming this is referring to the "Browse Folders" view,  @foundscapes with a potentially long list of folders to choose from, I think we would have a lot of accidents happen without the "Done" button. 

Also we are letting them know they can only connect to one project at a time without "telling" them. Having the check mark move from project to project if selecting multiple is, I think, less frustrating than expecting to be able to select multiple and being cut off. 

I'll let @cstiens weigh in too though

**Comment by cstiens** [comment]
@foundscapes are you referring to the browse project view?
