### ISSUE TITLE
Copy Media to Different Project

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/Save-app-ios#117]
@tladesignz I built out separate workflows for moving already uploaded media to a different project, and queued (WAITING) media to a project. A standing question I have is 

**_"Is metadata still attached to uploaded media that is being re-uploaded?"_**

If not, 

This is workflow for all -- 
![Add Queued Media-Workflow](https://user-images.githubusercontent.com/36669955/58352144-54ef2700-7e30-11e9-86f1-53686eafedc9.jpg)

If so, this is the separate workflow specifically for "Adding Uploaded Media to New/Connected/Browsed Project"

![Add Uploaded Media-Workflow](https://user-images.githubusercontent.com/36669955/58352189-7f40e480-7e30-11e9-8070-20f4f21cf164.jpg)

**Comment by kckthx** [comment]
Batch Edit Icon:
https://github.com/OpenArchive/openarchive-assets/blob/master/icons/batchedit.svg

**Comment by RaffiRincon** [comment]
If I want to start implementing this, is there something special I need to do other than clone master, work on it, and do a PR? I didn't see any other branches. I'm new to open source. So far I downloaded the project and configured it so that I'm debugging it on my device.

**Comment by tladesignz** [comment]
> If I want to start implementing this, is there something special I need to do other than clone master, work on it, and do a PR?

That would be the main workflow, yes!

I added some contribution guidelines to the readme, please have a look at them!

Thank you for your interest! Looking forward to your contributions!

**Comment by foundscapes** [comment]
@tladesignz this was never implemented...is this something we'd want to rethink for the new designs?

**Comment by tladesignz** [comment]
I don't think this makes sense. It would make the UI more complicated and the benefit seems dubious. 

In the rare cases, content might need to be uploaded to multiple servers or multiple folders on one server, users can just add that content from their original source again.

**Comment by foundscapes** [comment]
ok closing
