### ISSUE TITLE
Explore SOCKS proxy setting possiblity /options

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-ios#120]
Can we enable socks or http proxy setting on our current webdav/http client?

**Comment by tladesignz** [comment]
The app uses iOS' standard interfaces for networking.

When using WiFi, you can configure a proxy and it should be honored. (Settings App -> WiFi -> (i) of your used WiFi -> Configure Proxy)

Besides that, every app that provides a network tunnel Network Extension can be used, too.

Everything else needs to be added to the app itself, as no other app will run in parallel more than a few minutes.

This will blow up the number of dependent libraries and, with most solutions, languages and build systems, cause an administrative burden and weakens the focus of the app.

**Comment by johnhess** [comment]
Sounds like this is solved by the ability to use a proxy at the OS-level.  If we find a user needing a per-app proxy, let's reopen/reconsider.
