### ISSUE TITLE
Ensure background uploading is working

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-ios#126]
- ensure videos can upload when the user leaves the app, at least up to the 3 minutes mark
- ensure video upload resumes when the user returns to the app if the 3 minute mark expired
- ensure status of upload is tracked appropriately when upload completes in the background

**Comment by tladesignz** [comment]
Progress tracked in #127.

**Comment by foundscapes** [comment]
@tladesignz reopening since app stops once we navigate away/open diff app - background uploading should work

**Comment by foundscapes** [comment]
@tladesignz I did not forget - while it may not be fixable right now, this is an ongoing issue that we need to resolve somehow, someday.

**Comment by tladesignz** [comment]
Can we please keep tracking this in #198 instead of constantly reopening 5 year old issues?

And please stop assigning me tasks, which are totally underspecified. Provide texts! Provide some UX ideas! (Can be text-only. But something I can work with.)
