### ISSUE TITLE
Not able to see the Project without any media in Browse existing Projects

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#131]
Steps to Reproduce :

1. Launch the application
2. Create New Project
3. Again go to New and choose Browser Existing Project

Expected Result -
Should be able to select the newly created project which does not have any media

Actual Result -
In Browse Existing Project, the newly created project or the projects without any media in it is not available for selection

**Comment by tladesignz** [comment]
Yeah, the project folder is only ever created when media is uploaded.

@foundscapes, please decide if this behaviour is ok or if project folder should be created immediately.

**Comment by johnhess** [comment]
> We decided today that if there's an empty project, it should not show up for now.
