### ISSUE TITLE
Able to create the projects with duplicate name

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#134]
I tried creating the projects with duplicate names like one in small alphabets and the other with the same name but in Caps. I was able to create both of them successfully without any error

Attached is the screenshot :
![IMG-20190713-WA0004](https://user-images.githubusercontent.com/8190141/61171883-4e14a300-a59b-11e9-9bbe-0baf8996a5d0.jpg)

**Comment by tladesignz** [comment]
@foundscapes Should it be allowed to create project names which distinguish themselves just by different case? Technically, they are different.

**Comment by n8fr8** [comment]
I would say that allowing this would more likely cause user error than enabling some kind of subtle naming scheme.

**Comment by foundscapes** [comment]
+1 to @n8fr8

**Comment by johnhess** [comment]
I agree with the observation that similarly named folders could cause confusion.

However, I think the difficulty of implementing something that does this more generally than ASCII upper-/lower-case makes it unlikely to be a good ROI.  For example, non-EN languages have other "similar" characters (accents).  Unicode contains many [homoglyphs](https://en.wikipedia.org/wiki/Homoglyph).  Variations in whitespace might also count.  "Projects" can be created on back ends which might violate our requirements (e.g. I can simply create folders "Foo" and "foo" in NextCloud).

Unless this breaks something beyond potential confusion, let's skip this.
