### ISSUE TITLE
Localize for iOS

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#151]
With Localization Lab

**Comment by tladesignz** [comment]
@foundscapes: I pushed English and German to Transifex.

Find it [here](https://www.transifex.com/guardianproject/openarchive/localizable-strings/) and let the translations begin!

**Comment by tladesignz** [comment]
We now have Arabic, French, German, Persian, Russian, Spanish and Turkish. I'll close this for now. We should create a new issue, when we do another translation push.

**Comment by foundscapes** [comment]
So simplified Chinese is not done?
