### ISSUE TITLE
Add FileProvider support

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-ios#157]
This could also be interesting for our app, depending of the direction it should move:

With this, we can be a folder inside the "Files" app:

https://developer.apple.com/documentation/fileprovider

**Comment by foundscapes** [comment]
@tladesignz is this still relevant?

**Comment by tladesignz** [comment]
Since Save is very much focused on the whole upload process, it doesn't seem so.

Unless you want Save to become a media management tool, where it's supposed to store media in its app belly potentially forever.

I'd advise against that, though. This would probably mean, that Save would need to get a deeper connection to backends also, where the data is flowing back onto the device, too. That would mean to lose our focus.

**Comment by foundscapes** [comment]
gotcha, out of scope.
