### ISSUE TITLE
[Suggesstion] : Message / Notification should be displayed when we have selected upload only when you are connected to Wifi option

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#159]
When we have selected the option "Upload only when wifi is connected" and user have not connected to wifi and try to upload the media, a notification / message should be displayed stating to connect to Wi-fi . 

Currently, if we have selected the option "Upload only when wifi is connected' and not connected to wifi and try to upload the media, no notification is displayed and the media remains in "uploading" mode. This confuses the user as the status shows "uploading"

**Comment by foundscapes** [comment]
@purvi-ranawat is this still an issue?

**Comment by purvi-ranawat** [comment]
@foundscapes : The issue still exists

Tested on below environment :

OS : IOS 17.2
Device : Iphone XR
Build version : 3.1.0, build 93

**Comment by tladesignz** [comment]
Ok. So I tackled this from two sides:
Similar like the warning when there's no Orbot, although the user said there should, there's now also a warning when there's no Wi-Fi, although the user said there should.

Additionally, when there's no Wi-Fi or no Orbot, the header will now show "Waiting…" instead of "Uploading…".

Will be available in build 95.

Please advise if and how you want to have this improved further.

**Comment by purvi-ranawat** [comment]
The message is displaying ok. But in the message, the word "again" is trimmed from the bottom.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/244570ad-d256-4d63-b0e8-49e1cd423b86)


Environment details : 

OS : IOS 17.2
Device : Iphone XR
Build Version : 3.1.1, build 101

**Comment by tladesignz** [comment]
Yeah, this is what you get when you want to use another font so much. It's possible, but you get side-effects.

A fix will be contained in build 102.

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/de6d00fc-e5cd-4efd-970f-3234b572c9bb)


Environment Details : 

OS : IOS 17.2
Device : Iphone XR
Build Version : 3.1.1, build 103
