### ISSUE TITLE
In Camera Roll, Indicate items already Uploaded

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/Save-app-ios#16]
![oa-media-already-uploaded](https://user-images.githubusercontent.com/36669955/49612592-d0d0e200-f96a-11e8-9fc0-0a009ba0e68c.png)

**Comment by tladesignz** [comment]
See my notes regarding the image picker here:
https://github.com/OpenArchive/openarchive-ios/issues/15#issuecomment-445842847

Additionally: Please keep in mind, that a typical share workflow on iOS is via the so called "Share Extensions". Data we get via share extensions are copies, not references to originals.

So, an indication in the camera roll if something was uploaded or, might be sketchy, if you don't want to disallow sharing images and videos via the share extension. (Which I really would not recommend!)

**Comment by tladesignz** [comment]
This would mean to implement our own camera roll browser aka. image picker.

I therefor recommend to remove this from the current sprint. This is potentially huge.

For reference: See issue #15 for a list of other available image pickers. (Which probably don't have that functionality, too, but anyway...)

**Comment by johnhess** [comment]
This would be unblocked by support being added to the image picker selected in #15 (TLPicker).

**Comment by tladesignz** [comment]
> This would be unblocked by support being added to the image picker selected in #15 (TLPicker).

Yes, but really only nice to handle in the future, *if* the original developer accepts a pull request. Otherwise we will forever be doomed to keep our own version in sync with upstream. (Or don't progress there anymore.)

**Comment by foundscapes** [comment]
@tladesignz can we close?
