### ISSUE TITLE
Video exports are killed in the background

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-ios#165]
Then uploads never finish, because they're never get ready.

Need to show export going on and maybe a timeout with error?

**Comment by foundscapes** [comment]
definitely timeout with error if this happens, but it hasn't been a big problem these past few weeks

**Comment by foundscapes** [comment]
This is still a problem - uploads are not completing when app is in background - what can we do?

**Comment by tladesignz** [comment]
> This is still a problem - uploads are not completing when app is in background - what can we do?

Hm. I'm pretty positive I've done everything possible to grab as much background execution time as possible. This is a general problem on iOS which all apps suffer from.

Therefore, the only thing I'm worried about: Does the upload continue when the app comes into foreground again?

**Comment by johnhess** [comment]
When uploading a large video file (883MB .mov), the upload stalls at 19.6MB uploaded, even when the app remains in the foreground.

**Comment by johnhess** [comment]
Solutions to this could include supporting larger files or notifying users that their file is unsupported before attempting and failing.

**Comment by tladesignz** [comment]
In the meantime, I threw out 2 libraries which were standing in between this and now use `URLSession` directly.
Please test with next TestFlight v2.7.1, build 59.

Note: If you exit the app, all bets are off. It should (or better *might*) finish uploading, but that API is so wacky, it's more like a "pretty please, dear iOS".

**Comment by johnhess** [comment]
@tladesignz what should we expect/test for with these changes?  Is background uploading out of our control or are there well defined actions that should work?

**Comment by tladesignz** [comment]
What to expect:
- Uploads while app is in foreground should work.
- The last file uploading when going to background should finish, if the following conditions are met: 
  - Folder creation and metadata file upload finished, and actual content upload started *before* iOS decides to kill the app. Typically, the time allowed continued running in background is 3 minutes, but could be way less, e.g. in battery saving mode. (Or whatever Apple decides in the future.) You can see this condition in the management scene, when an item shows any amount of bytes already transferred.
  - Network speed is high enough to allow for this.
- Mutliple smaller files *might* finish uploading in background during the above mentioned 3 minutes grace period.
- Upload continues smoothly when returning to app.

Regarding our control: Yes, we don't have any control here. We're asking nicely and iOS typically grants us *some* time, most of the time and *might* finish a file upload for us.

**Comment by johnhess** [comment]
Thanks @tladesignz 

@purvi-ranawat (and Mike, when you get set up here), could you run the new version through its paces and comment here if you find that it's not behaving as Benjamin's previous comment expects?

**Comment by johnhess** [comment]
When you see this and hit retry, does that work?  

Or, if you hit "cancel", does the app upload the other videos, then retry the failed one? This is what happened for me, and it seems like a sensible retry strategy.

**Comment by purvi-ranawat** [comment]
@johnhess : 

1. After clicking on Retry, that particular video is uploaded. but after that video, uploading for other videos keeps on processing and not getting uploaded. 

2. After killing the IOS app, when we restart the app, the error for that particular video is displayed but for other videos, it starts uploading but then it keeps on processing and not getting uploaded

**Comment by johnhess** [comment]
I'm using 2.7.1 (59) and am not able to replicate the persistent failures.  If I kill the app, I do get that error indication and the same dialog you see.  But, whether or not I select "retry", the app manages to successfully upload all queued videos to NextCloud.

It's possible that part of the problem is https://github.com/OpenArchive/Save-app-ios/issues/196. 

@purvi-ranawat Given that this particular issue has morphed a few times and been mostly resolved, can you please create new bug tickets with detailed replication steps and expected/actual outcomes for the remaining failure modes?
