### ISSUE TITLE
Optimize for Dark Mode

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#168]
![signal-2019-10-18-092908](https://user-images.githubusercontent.com/2231711/67132994-bccb5300-f1bf-11e9-92cd-d5b4ba3a6091.png)

**Comment by n8fr8** [comment]
For now, let's just override dark mode as a quick fix:
https://developer.apple.com/documentation/xcode/supporting_dark_mode_in_your_interface/choosing_a_specific_interface_style_for_your_ios_app

**Comment by tladesignz** [comment]
Will be contained in build 47.
