### ISSUE TITLE
check how sha256 hashes are being encoded/stored

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-ios#170]
There is some confusion about how the sha256 hash is being generated and stored.

sha256sum IMG_0097.PNG
46755ae2aa617da685f6bff69afad5bfd4236127943bf6bc248deb5f1b577c50  IMG_0097.PNG

The metadata SAVE iOS uploads shows this:
{
  "originalFileName" : "IMG_0097.PNG",
  "dateCreated" : "2019-07-11T15:33:12Z",
  "hash" : "RnVa4qphfaaF9r\/2mvrVv9QjYSeUO\/a8JI3rXxtXfFA=",
  "contentType" : "image\/png",
  "contentLength" : 823338
}

**Comment by tladesignz** [comment]
Mine is BASE64 encoded. You want it to be changed to hexadecimal output?

**Comment by n8fr8** [comment]
Yes, I think that will be the easiest for people attempting manual verification of the hash, using standard utilities like sha256sum.

**Comment by n8fr8** [comment]
BASE16!

**Comment by foundscapes** [comment]
all about it!
