### ISSUE TITLE
make language tappable on first media upload screen

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#171]
Many people intuitively tap on the add your media language when first arriving on this screen after setting up server. Even though it says click the + below, I think it should be tappable.

**Comment by foundscapes** [comment]
Hmm.
Tested on Iphone xs ios 13
It doesn't seem to be working when I re-downloaded app, log in, don't choose a space OR do choose a space and then tap on "Tap buttons below to add media to your project" did you update or just close this @tladesignz ?

**Comment by tladesignz** [comment]
Of course it's not released, yet. Testers weren't set up on the new account, though. Just did that. You should have received a mail from AppStore Connect.

**Comment by foundscapes** [comment]
Ok - I didn't receive the email until 5 minutes ago....thanks!

**Comment by foundscapes** [comment]
Works great on xs ios 13 - will test more
