### ISSUE TITLE
Unpredictable orientation of photos on GoodCloud

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#172]
This only happens with photos, not video. Wondering if it is affected by photo being landscape vs portrait...will test on Android.

<img width="988" alt="Screen Shot 2019-11-19 at 9 09 12 AM" src="https://user-images.githubusercontent.com/2231711/69169222-dd334980-0aac-11ea-9514-39dc4a5136a0.png">

<img width="912" alt="Screen Shot 2019-11-19 at 9 11 45 AM" src="https://user-images.githubusercontent.com/2231711/69169223-dd334980-0aac-11ea-9498-a2c41369dfcc.png">

<img width="887" alt="Screen Shot 2019-11-19 at 9 11 56 AM" src="https://user-images.githubusercontent.com/2231711/69169397-271c2f80-0aad-11ea-9434-f32e6a2ef6b3.png">

<img width="843" alt="Screen Shot 2019-11-19 at 9 12 08 AM" src="https://user-images.githubusercontent.com/2231711/69169474-431fd100-0aad-11ea-8e50-b91c5ac31d84.png">

**Comment by tladesignz** [comment]
That is how it's seen on the server? And they are JPEG? Which software shows that? A browser? Shows original files or smaller preview-renderings of them?

Many devices store photos in landscape always. They just set a flag in the JPEG's metadata, that the display orientation was actually meant to be different. Some software doesn't honor these flags and renders smaller versions of that photo wrong or just displays it wrong. (Same can happen with color profiles, btw.)

It might well be, that we can't do anything about it, except recoding the photo. Which would mean, it *wouldn't be the original photo anymore*, technically. Typical dangers with that approach is also, that we accidentally lose metadata (inside the photo file) when doing so.

**Comment by foundscapes** [comment]
Ahh gotcha.

Saw this on GoodCloud Firefox 70.0.1 browser jpegs - orientation off for both smaller preview and OG files once clicking.

**Comment by n8fr8** [comment]
I think Nextcloud's web interface isn't "respecting the EXIF", as @tladesignz said. We definitely don't want to rotate/re-encode the photo.

**Comment by roseregina** [comment]
I am working on testing this, but I want to flag for the documentation for orgs that Next Cloud doesn't fully engage [no thumbnail, no viewer] with the .heic file format that the the iPhone 11 (and probably others) uses on the high efficiency setting. 

From what I can tell, this means that if you want or need to be able to see your images correctly in Next Cloud, you have to change this _before_ taking the photo: 
Settings > Camera > Formats
![image](https://user-images.githubusercontent.com/15040203/77102068-476de380-69e6-11ea-9ac6-65a617e8383e.png)

**Comment by johnhess** [comment]
This is a goodcloud issue, so closing.
