### ISSUE TITLE
Sharing from Voice Memos not working

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#174]
Inconsistent uploading of voice memos across iphones / servers - could it be GP's server has a limit? file is 48 mb

BUG - iPhone XS
iOS 13
guardianproject cloud

Audio files not showing up in Save whether choosing existing folder / making new folder, etc.

Steps:
1. open voice memos
2. select file
3. share to Save 
4. choose project
5. Click Import
6. Choose project
7. Click open Save popup to go to Save
8. Nothing is in preview
9. click upload, nothing happens then takes me back to project folder space
10. nothing is in project folder space to be uploaded
11. audio file not on server

WORKS fine on iphone 6s  w/ oademo.thegood.cloud
iOS 13

**Comment by foundscapes** [comment]
It definitely seems like a server issue but is confusing - when I tried uploading to cloud.guardianproject.info from iphone 6s, I couldn't do it, but when I tried uploading on iphone XS to oademo.thegood.cloud, it also didn't work...

**Comment by johnhess** [comment]
I am able to upload small audio files direct from iOS voice memos.  If it ends up that large files end up not working well, we can make a new ticket for that documenting specifics.
