### ISSUE TITLE
 Change first welcome screen language 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#175]
Need to find easy/fast way to mock up but it should read:

**_Save_** by OpenArchive

Share
Archive
Verify
Encrypt

**Comment by tladesignz** [comment]
You mean this one?
![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2019-12-17 at 11 37 12](https://user-images.githubusercontent.com/117089/70988164-9b082280-20c1-11ea-8d7d-32cfce4ff8fb.png)

Please provide a design mock and also consider that it should work with this screen size:
(You may need to click multiple times to finally see the original size...)

![Simulator Screen Shot - iOS 12 4 @ iPad Pro (12 9-inch) (3rd generation) - 2019-12-17 at 11 38 34](https://user-images.githubusercontent.com/117089/70988280-d4409280-20c1-11ea-9840-2e44ad864fe2.png)

**Comment by foundscapes** [comment]
Yes! Nathan has updated android, and it's 95% there now, but we need to add more space between Encrypt and "Secure Mobile Media..." to bring it lower and italicize "Secure Mobile Media...'
![576-1024](https://user-images.githubusercontent.com/2231711/71925102-26b32300-3145-11ea-9cb1-1b5ad5a7194e.png)

**Comment by tladesignz** [comment]
Will be contained in next build.
