### ISSUE TITLE
Add Dropbox support

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-ios#176]
People want it, it seems.

**Comment by tladesignz** [comment]
Implemented with 21fd6ba4d6442b0e5aa323345ef9bd8ac15f26bb, sans huge file support.

**Comment by tladesignz** [comment]
In TestFlight now!

**Comment by n8fr8** [comment]
what happens if a user tries to upload something larger?

**Comment by tladesignz** [comment]
> what happens if a user tries to upload something larger?

Error message explaining the situation:
"The Dropbox support can't handle files bigger than 150 MByte."

Did you implement the session'd upload in Android?

**Comment by n8fr8** [comment]
Hmm, maybe not! will dig in and make sure.

**Comment by n8fr8** [comment]
that said, I hope it is not too hard considering we already have the Nextcloud chunking support

**Comment by tladesignz** [comment]
> that said, I hope it is not too hard considering we already have the Nextcloud chunking support

Completely different.

**Comment by roseregina** [comment]
Is dropbox integration included in the app store? I have tried everything I can think of, including deleting and reinstalling and I only have WebDAV and Internet Archive options. 

![image](https://user-images.githubusercontent.com/15040203/77088395-64002080-69d2-11ea-9d37-9cb771a8cc66.png)

**Comment by n8fr8** [comment]
Not yet. It's only in testflight.

Also need to pass Dropbox approval for API access still.

Let's not test this yet.

**Comment by foundscapes** [comment]
Wait, I thought @tladesignz wanted us to test this? How do we move forward?

**Comment by roseregina** [comment]
Either way, it would be good for me to have access in testflight.

**Comment by foundscapes** [comment]
Agreed - please send @tladesignz your apple id to add on the thread I forwarded

**Comment by tladesignz** [comment]
> Agreed - please send @tladesignz your apple id to add on the thread I forwarded

new public beta Testflight set up. @roseregina is first on that list. Will take a while until Apple rubber-stamps it.

**Comment by tladesignz** [comment]
Implemented, tested, 2.6.0 will be released soon.
