### ISSUE TITLE
Images Missing from On-boarding Screens

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-ios#178]
iPhone 11, running iOS 13.4.1
Version 2.6.0 (51) in TestFlight

Expected Results: 
1. Install _**Save**_ and open it for the first time
2. See welcome screen and onboarding with images (similar to android, pictured below)
Android images: 
![image](https://user-images.githubusercontent.com/15040203/80258067-ecb05300-8647-11ea-82bb-34f3786fd18b.png)
![image](https://user-images.githubusercontent.com/15040203/80258122-136e8980-8648-11ea-9f89-8c8d2f3350a1.png)
![image](https://user-images.githubusercontent.com/15040203/80258151-21bca580-8648-11ea-8672-58ac008185a7.png)
![image](https://user-images.githubusercontent.com/15040203/80258177-34cf7580-8648-11ea-9b63-4b04b3511f37.png)
![image](https://user-images.githubusercontent.com/15040203/80258205-4153ce00-8648-11ea-8709-cf749dd096e6.png)

Actual Results: 
1. Install _**Save**_ and open it for the first time
2. See welcome screen and onboarding with images
iOS screens (please ignore dark mode versus Android light mode): 
![image](https://user-images.githubusercontent.com/15040203/80259115-72350280-864a-11ea-9ab4-7d4d620c18fd.png)
![image](https://user-images.githubusercontent.com/15040203/80259162-92fd5800-864a-11ea-95ec-e12a8ba2851c.png)
![image](https://user-images.githubusercontent.com/15040203/80259174-9a246600-864a-11ea-9620-ed2d7592e5a2.png)
![image](https://user-images.githubusercontent.com/15040203/80259194-9f81b080-864a-11ea-8141-1c40e7b8396b.png)
![image](https://user-images.githubusercontent.com/15040203/80259203-a5779180-864a-11ea-9e3b-0874609c45b7.png)

Note the lack of images for the onboarding information. 

Here are the onboarding assets: 
https://github.com/OpenArchive/Save-app-android/tree/master/art/onboarding

See also #179 about centering the dots on the bottom of the screen.

**Comment by roseregina** [comment]
Screenshots are from the MotoG, which has the considerably smaller screen than the other testing Androids. Please let me know if screen shots from a larger phone are needed.

**Comment by tladesignz** [comment]
Will be fixed in build 52.

**Comment by tladesignz** [comment]
Thanks for catching this!
