### ISSUE TITLE
Dots at Bottom on Onboarding Screen Should Be Centered

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-ios#179]
iPhone 11, running iOS 13.4.1
Version 2.6.0 (51) in TestFlight

Expected Results:
1. Install _**Save**_ and open it for the first time
2. See welcome screen and onboarding with progress dots centered at the bottom of the screen (similar to android, dots circled in pink below)
![image](https://user-images.githubusercontent.com/15040203/80260471-9c3bf400-864d-11ea-9f73-194544dce87b.png)

Actual Results: 
1. Install _**Save**_ and open it for the first time
2. See welcome screen and onboarding with progress dots left-justified at bottom of screen 
(iOS dots circled in pink below)
![image](https://user-images.githubusercontent.com/15040203/80260329-46ffe280-864d-11ea-936b-bfaf9c56ebd4.png)

**Comment by tladesignz** [comment]
Definitely not. iOS is the design reference here. The android implementation actually deviated from the design templates. 

Images will overflow to the bottom in certain circumstances (depends on screen size and orientation), so there's actually no space available in the center for the dots.
