### ISSUE TITLE
Fix Dropbox Logo (not urgent)

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-ios#180]
iPhone 11, running iOS 13.4.1
Version 2.6.0 (51) in TestFlight

The Dropbox logo is cropped on the in-app view and is using an old Dropbox logo. 
Current from app: 
![image](https://user-images.githubusercontent.com/15040203/80261047-01441980-864f-11ea-8ce4-2e88f39b7b86.png)
(left icon only, good cloud logo is for scale reference)

Current Dropbox logo from their website: 
![image](https://user-images.githubusercontent.com/15040203/80261115-26d12300-864f-11ea-8c72-828c77f3444e.png)

**Comment by tladesignz** [comment]
Will be contained in build 52. Thanks for catching this!
