### ISSUE TITLE
App crashes many times, when it's idle

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#184]
Device: iPhone XR
iOS: 14.8.1

App Crashes many times when it's idle. Pop up message for the same appears on the screen.
![IMG-9042](https://user-images.githubusercontent.com/8190141/158116563-20894e45-8c06-4ba8-a4f1-5e193ba180b5.PNG)

**Comment by tladesignz** [comment]
Thanks for sharing!

Seems in conjunction with #185, should be fixed in new TestFlight. Please reopen, if you'll experience this after the next build!

**Comment by johnhess** [comment]
@purvi-ranawat you should now be able to reopen issues.

**Comment by tladesignz** [comment]
Hrm. Could be due to this problem:
https://stackoverflow.com/questions/26688287/unable-to-understand-where-myapp-is-crashing

**Comment by tladesignz** [comment]
It seems, Apple tightened the screws on background execution and I didn't fully grasp what is to do earlier. I improved that now. Hope that fixes it. TestFlight underway. Please reopen/comment if you still experience this!

**Comment by purvi-ranawat** [comment]
@tladesignz Sure, will reopen if face the issue in new version
