### ISSUE TITLE
Uploading fails for drop box

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#185]
Device: iPhone XR.
OS: 14.8.1

Unable to upload anything on dropbox using iPhone. It goes on processing and finally fails. Attached is the screenshot IMG-9011.PNG
![IMG-9011](https://user-images.githubusercontent.com/8190141/158119012-54e74038-b50f-4072-85e4-25872f4858f5.PNG)

**Comment by tladesignz** [comment]
Yes, thank you very much! I started working on Save again last week and stumbled over that, too.

Fixed with a00a3695cf5ef476b4912606e37649b6c91fbec1. New TestFlight will follow soon!
