### ISSUE TITLE
The symbol for server Internet Archive looks very dull as compared to others

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#186]
@johnhess Tested on iPhone XR, App. version 2.7.0 (55)

Below is the screenshot:

![WhatsApp Image 2022-04-25 at 11 28 07 AM](https://user-images.githubusercontent.com/8190141/165029428-507ba828-740a-44ce-a941-70f9db66912c.jpeg)

**Comment by tladesignz** [comment]
Fix will be contained in next TestFlight.

**Comment by purvi-ranawat** [comment]
It works fine now.
![WhatsApp Image 2022-04-29 at 8 38 04 PM](https://user-images.githubusercontent.com/8190141/165972525-56177a2d-e397-4e7e-b774-25d9d03c3506.jpeg)
