### ISSUE TITLE
Error message gets displayed when trying to login to Internet Archive

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#188]
On clicking on "click here to login"  the error message "The operation couldn't be completed" message gets displayed.

Tested on iPhone XR, iOS 15.4.1
Save app version: 2,7,0 (56)

Attached is the screenshot
![WhatsApp Image 2022-04-28 at 2 44 56 PM](https://user-images.githubusercontent.com/8190141/165721306-5705459d-9da8-429e-bec6-36de2eef1240.jpeg)

**Comment by tladesignz** [comment]
Hm. Can't reproduce that now.

This error message is probably from here:
https://github.com/OpenArchive/Save-app-ios/blob/master/Save/Space/IaScrapeViewController.swift#L63-L70

That means, that website linked a resource (maybe some unimportant image or a script or the like), which couldn't be loaded.
That triggered an error, which our web view delegate then displays in an alert.

Not sure, what's the best way to improve the UX here. 

It might be important to inform the user, that the website didn't load properly and they should try to reload, or it could be completely trivial and unimportant to the user. Not decidable here.

@foundscapes, @johnhess: I recommend invoking Carrie's expertise for this. However, that is probably done within a bigger work package, as this seems a rather small issue.

**Comment by johnhess** [comment]
TY.  I think priority for this will depend on how frequently the issue comes up.  I'll mark it as low for now but comment/bump it up if this is a frequent failure mode.

**Comment by pkhivesara** [comment]
Standard practice for such scenarios is usually to show an alert with a message along the line: 'Something went wrong, please try again later.' If we would like to take this a step further, we could also add a 'Retry' action to the alert.

**Comment by foundscapes** [comment]
Solved in Save 2.0 ux udpate
