### ISSUE TITLE
Camera icon is not working

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#189]
Camera icon is not clickable when the user tries to add photo a project.

Tried on iPhone XR. iOS 15.4.1, app version 2.7.0 (57)

Attached is the screenshot
![WhatsApp Image 2022-05-04 at 6 34 31 PM](https://user-images.githubusercontent.com/8190141/166687574-6586c8f2-4788-43c7-9450-5514aacf2ebf.jpeg)

**Comment by tladesignz** [comment]
Great catch, thank you! 

Is this when you denied camera access?

That will be fixed in version 2.7.1, build 58.

**Comment by purvi-ranawat** [comment]
@tladesignz : Yes. I have denied Camera access when installed the app and it asks us the permission for the very first time. But after that Camera icon is always disabled. I think upon clicking on the Camera icon, it should again ask for the permission as the user might have forgotten about the denied Camera access

**Comment by tladesignz** [comment]
> @tladesignz : Yes. I have denied Camera access when installed the app and it asks us the permission for the very first time. But after that Camera icon is always disabled. I think upon clicking on the Camera icon, it should again ask for the permission as the user might have forgotten about the denied Camera access

Yes, as I thought. I implemented that.
I think the reason for this broken behaviour was, that the library used changed its API slightly.
