### ISSUE TITLE
Error message gets displayed when we try to use Browse existing projects to share any media or image

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#190]
Steps to reproduce:

1, Go to photo gallery or image gallery
2, Select any image and click on Share
3. Select Save>Dropbox>New Project >Browse existing projects

Expected result: List of existing projects gets displayed
Actual result: Error message gets displayed under Browse Projects

Tested on iPhone XR. iOS 15.4.1, App version 2.7.1 (58)

Attached is the screnshot:
![WhatsApp Image 2022-05-06 at 6 22 21 PM](https://user-images.githubusercontent.com/8190141/167135784-aad713ef-0f8d-4151-9352-039c29284607.jpeg)

**Comment by johnhess** [comment]
Users can work around this by adding a new existing project in the Save app, then selecting from the gallery.  Still very much a bug, but good to know it doesn't block every avenue.

**Comment by tladesignz** [comment]
Nice catch! Will be fixed in v2.7.1 build 59.

**Comment by purvi-ranawat** [comment]
It works fine in v2.7.1, build 59.
