### ISSUE TITLE
Should filenames reflect media creation timestamps?

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#195]
From [here](https://github.com/OpenArchive/Save-app-ios/issues/182#issuecomment-797343718):

1. We can use a different naming scheme on files, yes. Currently, on iOS we're using what the OS is giving us, if it's giving us any. If not, we're using a randomly generated UUID plus an extension which works for the file format.
2. There are different timestamps available. The filesystem has creation (always) and modification timestamps (mostly, but not always), and different file formats may contain other timestamps inside as contained metadata. We can definitely use the filesystem timestamps to create names, that's ok. About the metadata contained inside the file - that's going to get difficult, as not every file format has that and if so, they might not have the same meaning, and it will be difficult to write code to read that for a lot of different file types. Even so, there's the question if the file is really an original or something transcoded on import into the app, and that metadata might or might not differ from the original.
3. At last, there's the question of how to format that timestamp in the file name: Should we use a (technical) internationally unified format, should we hardcode a typical format of one region (like the US way of displaying a date and time) or should we localize to what the device is set to?

**Comment by johnhess** [comment]
If a user already knows a piece of media by name, they should be able to search for that name in their filestore and should be able to communicate with other collaborators about it by name.

Therefore, my 2c is we should not overwrite filenames we receive from the OS which may be meaningful.  The existing strategy of the UUID when there's no filename seems appropriate, too.  

If we want to store structured information, I would favor adding it to a structured store i.e. .meta.json.

I will close this ticket unless you object @foundscapes

**Comment by foundscapes** [comment]
solved for in Save 2.0 ux updates
