### ISSUE TITLE
Instead of actual ID some random number gets displayed under Dropbox logo

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#197]
When we sign up for Drop box using the email id, then email id should be shown as the dropbox id. But instead on IOS, some random number gets displayed as the dropbox id.

Attached is the screenshot:
![WhatsApp Image 2022-05-09 at 10 21 03 PM](https://user-images.githubusercontent.com/8190141/167459792-4f6ba638-5044-4223-8ded-e0b4689890e1.jpeg)

**Comment by tladesignz** [comment]
Will be contained in TestFlight v2.7.1, build 59.

**Comment by purvi-ranawat** [comment]
It works fine in the build 59
