### ISSUE TITLE
Size of same upload varies

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#199]
While a video is (waiting to be) uploaded, the file size changes.  In the uploads pane, I see the same file depicted as 49.1MB (the size it will eventually be when uploaded to dropbox) and 47.1MB and 43.4MB.  Perhaps during transcoding this is the size transcoded so far?

The video in these screenshots is 49.1MB in dropbox after successful upload and 28.5MB on the phone (presumably before transcoding).  In all cases, the file eventually ends up being described in the uploads pane as 49.1MB.

![image](https://user-images.githubusercontent.com/1799120/168943299-e2a42be1-3d8f-4858-9f9e-a75c253a9d76.png)
![image](https://user-images.githubusercontent.com/1799120/168943320-d1315c77-3dba-4dcc-98d4-2346c72caafd.png)

**Comment by johnhess** [comment]
I think it's a low severity issue, but it is confusing.  If I were a pay-by-the MB customer, and I uploaded a large video, then saw that in my upload list it said "20MB", I might happily go get some coffee.  Then I'd come back to find that my app used 800MB of data.  Then I would cry.

I agree we can't know the final file size til we have encoding finished.

In lieu of "size so far", how about a string indicating what's happening "Encoding file" or "Processing video" or the like?  If I had to pick, I'd say encoding because it is specific.  I'm open to other copy if you have something you prefer.

**Comment by tladesignz** [comment]
Yeah, that makes sense. Now clearer to the user what's going on and why nothing's uploaded, yet.

Will be contained in TestFlight build 61.

**Comment by purvi-ranawat** [comment]
@tladesignz  / @johnhess : Also, when we try to upload the image through sharing (Sharing through any app like photo gallery, Signal, etc), Encoding file is not coming. Instead we directly get the size of the file and the uploaded size. Only when we go to Save app and select media from there, then only Encoding file is coming

**Comment by johnhess** [comment]
Based on today's discussion, this is working as intended since encoding happens in the share context.
