### ISSUE TITLE
Upload mysteriously disappears if you navigate away from the app

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#200]
To replicate:

1. Upload a file to an existing NextCloud project (this one was a >150MB video to sam.nl.tab.digital)
2. Once the file appears in the project view, leave the application
3. Reopen the application.

*Expected:* The file is either queued, uploading, uploaded, or failed (depending on network and time elapsed)
*Actual:* The file does not appear in the project view nor the "uploads pane"

These screenshots taken in sequence: 
![image](https://user-images.githubusercontent.com/1799120/168947535-86f6fdf5-08eb-4ddf-a203-00d35865bf28.png)
![image](https://user-images.githubusercontent.com/1799120/168947543-6865b8b3-88a9-4704-9ca9-79b986d4185f.png)

iPhone 13 Max, 2.7.1 (59)

**Comment by johnhess** [comment]
This same file uploads just fine (at 273MB) when the app is in the foreground.  If I wait for it to start uploading (i.e. the size uploaded is non-zero), it does not disappear.

**Comment by tladesignz** [comment]
Ok, so I added code which requests background time when importing videos, that already helps.

Additionally, I added code, which tries to restart asset import, if it stopped. That could have become unavailable at that time, but then the user will get an error feedback.

So everything should be much clearer now!

**Comment by tladesignz** [comment]
@purvi-ranawat, please test with next TestFlight! (will be build 60)

**Comment by purvi-ranawat** [comment]
@tladesignz @johnhess Not able to reproduce the issue on iPhone XR for app version 2.7.1 (61)
