### ISSUE TITLE
On reinstalling the app existing projects are not displayed for Internet Archive

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#201]
Steps to reproduce:

1. Create some projects on Internet Archive server
2. Upload some images or media
3. Uninstall the app or remove Internet Archive server
4. Reinstall the app and Internet Archive server and login with old credentials used earlier
5. Go to Browse existing projects

Expected results: Existing projects should be displayed 
Actual result:: Only New Project screen gets displayed.

IOS version: 15.4.1, App version: 2.7.1 (59)

Note: It works fine for Nextcloud and Dropbox

**Comment by tladesignz** [comment]
Yes, this is a limitation of the Internet Archive's API. We can't do anything about that.
