### ISSUE TITLE
IA Signup flow: Option to create a new API key should be presented first, not existing API key flow

### ISSUE THREAD

**Issue by huertanix** [OpenArchive/Save-app-ios#206]
At the moment, the first thing a new user is presented with in the IA setup flow is something that looks like a login screen but asks for an `Access Key` and `Secret Key`, neither of which are familiar words for most people, since many have never used or have heard of an API before. See:

![save_api_key_ia](https://user-images.githubusercontent.com/72914/171089567-b620ba71-3498-4c20-ac04-c299c3c60eb5.png)

It may be worth exploring changing this step in the flow so that the user is first presented with the option to generate a new API key first, with maybe some text explaining that this will be a one-time process.

Then maybe leave a small "Use an existing Internet Archive API Key" (or similar verbiage) link to this existing API keys screen somewhere at the bottom, for the presumably smaller contingent of users who already have an IA API keypair.

**Comment by huertanix** [comment]
At present, the existing flow copies API keys from an in-app webview and puts them into these fields, so the app is already very near the API credentials. If you mean the IA username and password though, then yes, currently the app doesn't touch those, but has the technical capability to do that. I'm not partial to Save directly asking for IA credentials but this would be a discussion to have with IA on whether there would be a way AI could offer access to some of IA's features via third-party apps like Save.

**Comment by tladesignz** [comment]
> At present, the existing flow copies API keys from an in-app webview and puts them into these fields, so the app is already very near the API credentials. If you mean the IA username and password though, then yes, currently the app doesn't touch those, but has the technical capability to do that. I'm not partial to Save directly asking for IA credentials but this would be a discussion to have with IA on whether there would be a way AI could offer access to some of IA's features via third-party apps like Save.

Hm. I guess, I forgot to write explicitly, what I implicitly meant:

"The app doesn't want to get near the credentials, **except** when the user expressly wants it to do so."

 That's why all the explanation is there and an extra button press is necessary before the process begins.

**Comment by johnhess** [comment]
One potential improvement here is to have the CTA to "Acquire Keys" go away once they've been acquired.  Then the "Connect" action is clearly the next thing you can do... 

Let's leave this one on hold til we get a design person in (soon, if all goes to plan).

**Comment by foundscapes** [comment]
solved for in Save 2.0 ux updates
