### ISSUE TITLE
Adjust swiping gestures in various dialogs (login to IA, select photo permissions) 

### ISSUE THREAD

**Issue by huertanix** [OpenArchive/Save-app-ios#207]
Some of the dialogs in the iOS app, namely the webview that pops up when creating a new IA API key, and the photo permissions dialog that opens when choosing a photo to give Save permissions to read, get accidentally dismissed by scrolling slightly too hard during testing, forcing the user to start over. I'm not sure if this is an iOS default swipe behavior for those kind of components, but it would be great to configure the swiping gestures attached to it, to make it less prone to accidentally swiping away.

**Comment by foundscapes** [comment]
solved for in Save 2.0 ux updates
