### ISSUE TITLE
Reconsider IA Login Flow

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#209]
Today, there are a handful of issues (e.g. #208, #206 and #188) in the IA login.  Some of these issues are difficult or impossible for us to address on our own.

This ticket is for a broader redesign of how IA's login works.

**Comment by tladesignz** [comment]
Also consider #211, when doing redesign.

**Comment by foundscapes** [comment]
solved for in Save 2.0 ux updates
