### ISSUE TITLE
Support Dropbox Uploads >150MB

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#210]
Per discussion on #196:     

> Yes, this is a limitation of the current Dropbox support. If you hit the red (!), the error message given will explain that. The limit is 150 MByte.
> There is a complicated support for larger files which includes using some "upload session", but I didn't use that at first, as it would clearly not work in the background and it was a whole lot to implement.
> We probably should revisit this, now that we positively know that we cannot ever support background upload anyway.

Let's add support for these larger foreground uploads

**Comment by tladesignz** [comment]
Will be contained in TestFlight build 63!

**Comment by purvi-ranawat** [comment]
@tladesignz It works fine for build 65.
