### ISSUE TITLE
Only show batch edit protip when multiple photos are being uploaded

### ISSUE THREAD

**Issue by huertanix** [OpenArchive/Save-app-ios#212]
When getting ready to upload a single photo, I was shown a message about being able to edit multiple uploads' metadata at the same time. However, I was only uploading one photo in this instance. Consider changing this message to only appear when multiple items are being uploaded.

**Comment by tladesignz** [comment]
Will be available in next TestFlight (build 63).

**Comment by huertanix** [comment]
Tested. Confirming that the batch edit no longer appears when only one media file is uploaded. I also tried uploading two files at once (one photo, one video), but it didn't appear that time. To clarify on this prompt's expected behavior, is it only supposed to appear once on first use and not on every multiple-file upload?

**Comment by tladesignz** [comment]
There was a problem where the alert was attempted to be shown before the scene was actually done rendering, so in effect it was never displayed. Now fixed.

Please test on next TestFlight build 66.

**Comment by purvi-ranawat** [comment]
@tladesignz  Batch edit protip does not appear for multiple uploads, for build 66.

**Comment by tladesignz** [comment]
Oh, man. This time, it *really* should work under all circumstances... (In build 67!)

**Comment by purvi-ranawat** [comment]
@tladesignz Protip appears only once when the app is installed. Afterwards, it does not appear for any of the servers.

**Comment by tladesignz** [comment]
> @tladesignz Protip appears only once when the app is installed. Afterwards, it does not appear for any of the servers.

Yes, that's the hole point of all the tips. They only appear once.
