### ISSUE TITLE
Project names show up in wrong server

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#214]
Replication:
1. Log into dropbox.  Create a project or open an existing one.  Example pictured here: "Second Project"
2. Log into IA. Create a new project.  Example pictured here: "John 271 Test"

Expected: When in IA, I see only the IA project.  When in Dropbox, I see only the dropbox project. 

Actual: They appear in each others' view
![2022-06-08 15 53 53](https://user-images.githubusercontent.com/1799120/172716323-98ad2c18-b48f-4135-a096-cb989bded7f4.png)
![2022-06-08 15 53 36](https://user-images.githubusercontent.com/1799120/172716329-710d0434-09d8-43cc-a825-2ec41b553ebd.png)
.

Tested on Production App Store version 2.7.1
iPhone 13 Pro Max/iOS 15.5

**Comment by tladesignz** [comment]
Will be contained in TestFlight build 63!

**Comment by purvi-ranawat** [comment]
@johnhess @tladesignz It works fine on build 63
