### ISSUE TITLE
Images / Videos selected for upload for one space are also seen in another space

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#218]
Steps to Reproduce : 

1. Open Save App
2. Connect to two or more spaces (for eg. dropbox and internet archieve)
3. One first space, select few media for upload
4. While the media is uploading in first space, select another space

Expected Result : 

Media selected for the first space should not be seen  in another space

Actual Result : 
Media selected for the first space are also seen in another space 

Attached is the video :  

https://user-images.githubusercontent.com/8190141/176665389-af397d45-612c-4b19-b902-5055f071e167.mp4

**Comment by tladesignz** [comment]
I'm sorry. This DB abstraction is such a mess and something seems to have changed recently, which creates this avalange of little changes.

Please test with next TestFlight build 66.

**Comment by purvi-ranawat** [comment]
It works fine on build 66.
