### ISSUE TITLE
Editing of the images is not working after batch edit

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#219]
Describe the bug : 

When we try to upload multiple images and videos and while the media is getting uploaded, when we select few of them and click on Edit. I am able to edit the information on those images. But once I edit them, when we select another batch of media for editing, fields for edit are not displayed.

Steps to Reproduce : 

1. Open Save App
2. Add few medias to the project (10 or more) and upload
3. Select 2-3 medias and click on Edit
4. Edit the information and click on Done
5. Now select another 2-3 images or videos which are not yet uploaded and click on Edit

Expected Result : 
Information fields should be available for editing for the media

Actual Result : 
Not able to edit the information. The fields for editing are not displayed

Environment :  

Device : Iphone XR
OS : IOS 15.4.1
Build : 2.7.2 (65)

**Comment by tladesignz** [comment]
Oh, I see. There's no edit after upload started. The real bug is, that batch editing actually is allowed on currently uploading items. Will fix that.

**Comment by tladesignz** [comment]
Will be fixed in TestFlight build 66.

**Comment by purvi-ranawat** [comment]
It is fixed now as Batch edit is allowed only on preview page. Tested on Version 66.
