### ISSUE TITLE
Edit is not working for single image / Video

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#220]
Steps to Reproduce : 
1. Open Save App
2. Add few medias to the project and Upload
3. select the image / video and click on Edit

Expected Result : 
Fields should be shown for Editing for images

Actual Result : 
Fields are not available for Editing for single image / video

Environment : 

OS : IOS 15.4.1
Device : iphone XR
Build : 2.7.2 (65)

**Comment by tladesignz** [comment]
@purvi-ranawat, to clarify:

You want to edit media information *after* you started the upload?

If that's the case, well, that is not a bug, but a feature.

This is not a synchronization tool, but an upload organization tool. We don't have control of the server side. A lot of things could happen there, including, not actually being able to overwrite things.

Therefore, after upload, no edits.

**Comment by purvi-ranawat** [comment]
@tladesignz If I upload multiple items and try to edit any single item (for which upload has not even started) it does not allow me to edit anything.

**Comment by tladesignz** [comment]
Yes. That's how it should be.

This is related to #219.

There's only one bug here: That batch editing is still possible for items already in the upload queue. Will fix it with #219.
