### ISSUE TITLE
"Project Already Exists" when browsing then selecting existing project

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#221]
To replicate:
 1. Fresh install
 2. Add a NextCloud instance with at least one existing project
 3. Browse existing projects within that nextcloud instance, selecting one of the pre-existing ones

Expected behavior: I can now upload to the preexisitng project. 

Actual behavior: I get an error message "Project Already Exists: Please choose another name/project or use the existing one instead"

**Comment by tladesignz** [comment]
Sorry, but I can't reproduce this.

You get this error, when you try to add a project, which you already have added.

I tried to do this on an old install. Worked.
I tried to do this on a fresh install. Worked.
I added a project, which' name was the same as on another server. Worked.

Something must be different on your end. Can you try once more and look out for other differentiating factors?

**Comment by johnhess** [comment]
Oddly, I am unable to replicate this today.  Near as I can tell I am running exactly the same version (2.8.0) from test flight.  I'm closing this as unable to replicate for now, and we can re-open if we see it again.
