### ISSUE TITLE
Delay after creating a new project before being able to upload images.

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#223]
When creating a new project within a newly-added NextCloud instance in test flight 2.8.0, there's a few seconds between creating the new project and the + to add images working properly.  If you click the + too early, you are taken back to the menu for creating a new project (or selecting an existing one). 

After a moment (~2s), the name of the newly created space appears on my screen and the + (to add media) button acts normally.

**Comment by tladesignz** [comment]
I only see this on the first run of the app. This pretty much looks like another symptom of #222. Progress tracked there.
