### ISSUE TITLE
"Orbot not running" message shown even when "Transfer via Orbot only" is not selected.

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#224]
I assume this is only meant to be shown when the selector under "Data Usage" is selected.  If this is WAI, let me know.

**Comment by tladesignz** [comment]
Will be fixed in TestFlight build 69.

**Comment by purvi-ranawat** [comment]
Now, Orbot not running message is not getting displayed even when Transfer via Orbot only is enabled and Orbot is not started

**Comment by tladesignz** [comment]
🤦 Database race condition. Sorry. Will be contained in TestFlight 71.

**Comment by purvi-ranawat** [comment]
@tladesignz  It works fine for build 71. Tested on iPhone XR. OS version 15.4.1
