### ISSUE TITLE
Need eye icon to view pw when setting up backends (nextcloud/dropbox)

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-ios#225]
[Same issue on Android](https://github.com/OpenArchive/Save-app-android/issues/369)

**Describe the bug**
Unable to view pw when logging into backends via app

**To Reproduce**

1. Go to: Private server/set up new server
2. Enter login credentials

**Expected behavior**
There should be an eye icon to click on the PW field in order to ensure you entered the pw correctly

**Actual behavior**
There is no eye/no ability to view password entered. This is especially important If login fails and it is bc of an incorrect pw, there is no way to view password

**Comment by johnhess** [comment]
CC @foundscapes

**Comment by tladesignz** [comment]
Contained in TestFlight build 70 arriving later today.

**Comment by purvi-ranawat** [comment]
@tladesignz Functionality is reversed, when we click on show icon it does not show password. but when the eye icon is crossed over password is displayed.

**Comment by tladesignz** [comment]
Will be contained in TestFlight build 72.

**Comment by foundscapes** [comment]
Thanks for fixing! can we close this @tladesignz ?

**Comment by tladesignz** [comment]
> Thanks for fixing! can we close this @tladesignz ?

Yes!
