### ISSUE TITLE
Retest latest build 73 before release

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-ios#226]
Since iOS 16 and Xcode IDE 14 came out recently, I did a rebuild for/with these.

The new IDE version also showed new warnings, which I fixed. But that means I changed some internal code.

@purvi-ranawat, can you please do a test with the latest TestFlight build 73, so we can finally get the release out the door?

Thank you very much!

**Comment by tladesignz** [comment]
First result: #227

**Comment by tladesignz** [comment]
@purvi-ranawat, I fixed #227. Are you through with this test? If so, I'll do another build and TestFlight.

**Comment by purvi-ranawat** [comment]
@tladesignz : I am done with the test. You can do another build now on IOS

**Comment by tladesignz** [comment]
Great! Save TestFlight with build 74 is released.

I close this now, since we've got this other issue to track progress. When you confirmed the fix, this version is finally ripe for release! Yeeeha!
