### ISSUE TITLE
App crashes on clicking on the significant content flag for any media

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#227]
App crashes when we click on significant content flag for any media for any of the server

Attached is the video : 

https://user-images.githubusercontent.com/8190141/193729057-a7147b06-7e88-4018-aa64-5d85fb913930.mp4

Device : Iphone XR
OS : IOS 16.0.2
Build No : 73

**Comment by tladesignz** [comment]
Fixed in build 74.

**Comment by tladesignz** [comment]
Thanks for catching this! Well done!

**Comment by purvi-ranawat** [comment]
It works fine on build 74.
