### ISSUE TITLE
About Save and Privacy links are not working

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#229]
On Menu page under Info Privacy and About Save links lead to 404 errors.

Steps to reproduce:
1. Go to Menu page on Save app.
2. Under info click on About Save or Privacy links

Expected results:
Privacy or About Save page should be displayed.

Actual results:
404 error gets displayed.
Tested on iPhone XR OS 16.0.2. Save version 74

![66432](https://user-images.githubusercontent.com/8190141/197163062-e8eaaea4-d608-4262-87ff-2e21f20708dd.jpg)

**Comment by tladesignz** [comment]
Somebody obviously changed something on the server. Hrrrrgrml.

Will be fixed in build 75.

**Comment by purvi-ranawat** [comment]
@tladesignz  It works fine  for build 75.
