### ISSUE TITLE
Need bug/feature/vuln templates set up for ios issues

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#231]
<img width="1114" alt="Screenshot 2023-01-24 at 12 36 17 PM" src="https://user-images.githubusercontent.com/2231711/214404086-0e92bda4-66b8-4e03-b4e9-8266367757f5.png">
Can we implement this for ios too? It saves a ton of time and helps contributors give us what we need.

Thanks!

**Comment by hiromipaw** [comment]
This was done.

**Comment by foundscapes** [comment]
Thank you @hiromipaw !
