### ISSUE TITLE
server url disappearing after entering into field

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#232]
**Describe the bug**
When I enter the server url into the field on the login screen (screenshots attached below), when I hit "done" or "next" on the keyboard, the url disappears

**To Reproduce**
1. Go to "connect your space"
2.  "private (webDAV) server"
3. Enter server URL https://nx27277.your-storageshare.de/remote.php/webdav 
4. the url disappears when trying to move to next step

**Expected behavior**
I would expect the server URL to stay in the field when I go to enter user name/pw

**Screenshots**
![IMG_4768](https://user-images.githubusercontent.com/2231711/214405907-8749a0cd-86c4-4a6c-aaad-0e248632dcab.PNG)
![IMG_4769](https://user-images.githubusercontent.com/2231711/214405928-2b26e468-7d93-4a69-b1cf-d995730871b4.PNG)

**Environment (please complete the following information):**
 - OS version: ios 16.2
 - Device: iphone 12 mini
 - App Version 2.8.2

**Additional context**
@purvi-ranawat can you test on other ios devices to see if this is reproducible?

**Comment by tladesignz** [comment]
Sorry, but I cannot reproduce this, not on other versions, not on an emulated device set up exactly like yours, nor on my iPhone 13 Pro @ iOS 16.3.

When you say

> the url disappears when trying to move to next step

what exactly does "move" mean? Can you get more precise on that? Like, do you use the keyboard button, or do you tap somewhere else? If so, where?

Did you enter the address completely by software keyboard or did you use some other means? E.g. copy-paste or a hardware keyboard?

**Comment by purvi-ranawat** [comment]
@foundscapes / @tladesignz : I am not able to reproduce the same on iphone XR (OS-16.2). For me, the URL remains as it is on entering the username and password or moving to next field. After saving the details and coming back on the Login screen also, the URL remains and does not disappear

**Comment by foundscapes** [comment]
@tladesignz see video below - when I leave that field and tap on the next field to enter username, the url disappears - I'm using this link: https://nx27277.your-storageshare.de/remote.php/webdav  
- one other thing to note is that I am already connected to this server so I see two issues:
1. we should be able to login to the same server with different user names
2. I do not have this issue when I disconnect from that server so if it's not possible to login to the same server with different usernames - we need a popup that says: you are already connected to this server - but, ideally, we can fix it so we can login to two different accounts on the same server.

https://user-images.githubusercontent.com/2231711/216695196-9d6677a0-5510-44ad-a447-6b8672c2e9a9.MP4
@purvi-ranawat glad it's working for you -

**Comment by tladesignz** [comment]
Ok, just tested this again.

The information about, that you added the server a second time was interesting.

However, I can still not reproduce this.

Not on a simulator, not on a real device.

The feature you ask for, namely using a server with the same credentials in multiple spaces works for me.

I'm confused and sorry.

There must be something, which is different between you and me. Something specific you do or some condition which is different. Any idea?

**Comment by tladesignz** [comment]
(BTW: your video is not working, @foundscapes!)

**Comment by foundscapes** [comment]
> Ok, just tested this again.
> 
> The information about, that you added the server a second time was interesting.
> 
> However, I can still not reproduce this.
> 
> Not on a simulator, not on a real device.
hmm do you have access to an iphone 12 mini? I wonder if it's somehow specific to this phone...same version 16.2 ios?
> 
> The feature you ask for, namely using a server with the same credentials in multiple spaces works for me.
> 
Good!
> I'm confused and sorry.
> 
> There must be something, which is different between you and me. Something specific you do or some condition which is different. Any idea?

No clue, sorry!

**Comment by foundscapes** [comment]
> (BTW: your video is not working, @foundscapes!)

really? It's working fine for me from this link: https://user-images.githubusercontent.com/2231711/216695196-9d6677a0-5510-44ad-a447-6b8672c2e9a9.MP4

**Comment by foundscapes** [comment]
@tladesignz aha I think the issue is that the video doesn't play on Safari, it works fine on Firefox, try that?

**Comment by tladesignz** [comment]
> @tladesignz aha I think the issue is that the video doesn't play on Safari, it works fine on Firefox, try that?

Hahaha! OMG, you're right! Sorry.

Ok, watched your video. You do copy paste, I see. I played around with a lot now. Even switched to English. No idea what's happening there with you. I cannot, for my life, reproduce it:

https://user-images.githubusercontent.com/117089/217521976-8735183e-2c60-467a-97c9-6d8d681d9306.mov

**Comment by foundscapes** [comment]
I'm glad you can't reproduce it, but concerned that I can't get any other outcome. @purvi-ranawat do you have an iphone 12 mini you can test on? It does seem specific to me, but worried that it hasn't been resolved. I'll test again with next release.

**Comment by foundscapes** [comment]
@tladesignz I'm glad you can't reproduce but I can't log in a second time once I'm logged into the same hetzner account. I am able to login and browse/create projects, which is on the critical user path, so this is not a big issue, just odd! We can move this to future problems if you want. thanks!

**Comment by foundscapes** [comment]
@tladesignz it happened again, but this time I wasn't already logged into hetzner. 
At first I tried using the shortened URL after putting in my username, but that didn't work. Then I added the pw, but it didn't show up on the screen, but after that, I was able to paste in the URL and go to the next project screen. 

The good news is that I was able to enter the server in AFTER entering my username/pw creds so it's usable but clunky/odd.
My screen video is too big to add here, but here is the link:  https://youtu.be/NG08xiM8hMU

**Comment by tladesignz** [comment]
Ahahaha! Now I got it! You had whitespace/newlines at the beginning or the end of your copy-pasted string, did you? I added code to remove that.

Try again with the next TestFlight later today! This should work with build 77 (version 2.9.0) and later!

**Comment by foundscapes** [comment]
Wonderful! I also haven't had the problem for a while now so will close this issue. Thanks all! great detective work
