### ISSUE TITLE
Implement new getting started screen

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#235]
The new getting started screen will offer 3 options (nothing new here)

- Weddav
- Dropbox 
- Internet archive

![Get Started Screen](https://github.com/OpenArchive/Save-app-android/assets/1177650/229dcb29-f2b5-4190-9a43-845f49ea27ee)

The progress bar indicates the three steps in the setup process of each backend.

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in next version 3.0.0, build 84.

**Comment by purvi-ranawat** [comment]
@tladesignz : On New Getting started screen, "space" should be replaced with "server" as per the new requirements

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/c6d88670-c5a5-4d90-9132-949e84c2c2be)


Environment : 

OS : IOS 17.2 
Device : Iphone XR
Build version : 3.0.0.build 84

**Comment by tladesignz** [comment]
@purvi-ranawat, awesome job! Thank you! Fix will be contained in version 3.0.0, build 85.

**Comment by tladesignz** [comment]
No worries, @purvi-ranawat, thanks for your diligence!

This will be fixed in version 3.0.1, build 88.

**Comment by purvi-ranawat** [comment]
@tladesignz It is working fine. Tested on iPhone XR, OS 17.2, app version 3.0.1 build 89.
