### ISSUE TITLE
Implement new dropbox setup

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#237]
Dropbox setup is implemented in 2 steps:

![Dropbox - Log In](https://github.com/OpenArchive/Save-app-android/assets/1177650/b61cd335-92eb-445f-a209-bf342535df1f)
![Dropbox - Success](https://github.com/OpenArchive/Save-app-android/assets/1177650/7b1176b6-0733-4526-b960-e13cac7a2245)

Light gray dropbox text:
background: #9F9F9F;

Button typography:
```
//styleName: 16pt;
font-family: Montserrat;
font-size: 16px;
font-weight: 600;
line-height: 20px;
letter-spacing: 0.01em;
text-align: left;
```

![Icon](https://github.com/OpenArchive/Save-app-android/assets/1177650/b1b45c21-2ccc-459c-a65e-3f01614fbb16)

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment]
@purvi-ranawat: This will be contained in version 3.0.0, build 84.

**Comment by purvi-ranawat** [comment]
![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/9c590ea2-973b-4d80-bdb7-6979ae025681)



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/3fc4000f-4cc0-44cc-8b31-9a9f5a0f4701)

@tladesignz it works fine. Testsed on iPhone XR. iOS 17.2, App version 3.0.0 build 84
