### ISSUE TITLE
Implement new image selection 

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#240]
With the new image selection flow images are highlighted when selected (previously only the border would be in green):

![Selected Image](https://github.com/OpenArchive/Save-app-android/assets/1177650/03dfd34a-4dce-4ddd-b9e0-45c7a8a1d7fe)

Once some images are selected the user can add more from the bottom menu or just upload the added media:

![Preview Images](https://github.com/OpenArchive/Save-app-android/assets/1177650/faadb5b0-967d-451b-a1cf-c0bda126ab99)

Clicking on an image allows the user to edit info for that media:

![Preview Images - Instructions](https://github.com/OpenArchive/Save-app-android/assets/1177650/a6a0b75b-8262-4296-b43a-82312e90d731)

If the user decide to upload the medias directly a warning is displayed: 

![Upload - Instructions screen](https://github.com/OpenArchive/Save-app-android/assets/1177650/456c5014-a1c7-4c92-be58-a42cde33680b)

Media information can be edited for multiple of single files by selecting one or more files:
![Preview Media](https://github.com/OpenArchive/Save-app-android/assets/1177650/a7daf643-7016-4801-b483-4c387627f64e)

For single media:
![Single Media Info](https://github.com/OpenArchive/Save-app-android/assets/1177650/cf3c2bd7-3854-4471-aa58-898835855f2f)

For multiple media at once:
![Multi Media Info](https://github.com/OpenArchive/Save-app-android/assets/1177650/23ce5d7b-959b-4e4d-96dc-5b794952732e)

Information is added in a form:
![Adding Info - Instructions](https://github.com/OpenArchive/Save-app-android/assets/1177650/9a1ed7d6-39c1-4e5e-a761-e33ae6f3ebb6)

If back button is pressed a warning is displayed:
![If pressed back](https://github.com/OpenArchive/Save-app-android/assets/1177650/a401fd90-e2e2-4a9e-b10e-2a7bf5cf7e48)

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment]
> @tladesignz :
> 
> 1. When we select the image, it is not highligted. Like in previous version, only Green border is displayed.

Yeah. The media picker is a third party library, which we won't meddle with. That would drive up costs for maintaining a fork for no serious gain.

> 2. "Add More" text is not displayed on the Upload screen like given in the requirements for adding more media. Only "+" sign is displayed in the bottom bar to add more media 💯

True. The iOS UI element used here isn't capable of displaying buttons with text + icons. The UX of iOS is well thought thru, so this is probably a very deliberate decision.
If this is sooo important, we would need to replace the preexisting tools with home-made stuff which I really don't want until somebody finds this so important that they either make me do it anyway, or have a really convincing argument.
So, I won't change this until somebody throws an explicit issue about it at me.

> 3. On the Edit screen after making the changes, when we press the back button, no warning is displayed. As per the requirement, below text should be displayed :

While implementing on the Android side, we came to the conclusion, that this is a rather stupid UX. Everything is stored, always. The users cannot lose data, so no warning necessary.

Thank you, @purvi-ranawat, for your diligence!
