### ISSUE TITLE
Implement space settings

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#242]
For dropbox:

![Dropbox](https://github.com/OpenArchive/Save-app-android/assets/1177650/04a09900-45cc-4c21-b3b3-0f9a24fed6e1)

For internet archive:

![Internet Archive](https://github.com/OpenArchive/Save-app-android/assets/1177650/702ab124-910c-4b56-9a69-95be1f3c3c3e)

For private webdav server:

![Private Server](https://github.com/OpenArchive/Save-app-android/assets/1177650/c86fc042-ede1-4f48-8efc-dc95784f6c6e)

**Comment by tladesignz** [comment]
@purvi-ranawat: This will be contained in version 3.0.0. build 84. (Which I'll push for TestFlight now!)

**Comment by purvi-ranawat** [comment]
@tladesignz This is working fine. Tested on iPhone XR iOS 17.2, app version 3.0.0 build 86
