### ISSUE TITLE
Implement new tagging options for medias

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#244]
In previous versions of Save we add more tagging options when adding metadata to images.
Now we only have:
- Location
- Name for the media
- Notes

![Single Media Info](https://github.com/OpenArchive/Save-app-android/assets/1177650/3f6b0799-dce2-4dcc-80c3-9800d666aca6)

**Comment by tladesignz** [comment]
@purvi-ranawat, this is contained in already released version 3.0.0, build 83.

**Comment by purvi-ranawat** [comment]
@tladesignz "Name for Media" is not getting displayed.

![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/04c5a869-92cc-4d38-a0b1-7024c2a97d58)

**Comment by foundscapes** [comment]
@purvi-ranawat good catch! we decided not to include that after the designs were made.
