### ISSUE TITLE
Add a new folder to a backend

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#246]
See https://github.com/OpenArchive/Save-app-android/issues/437

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in version 3.0.0, build 84.

**Comment by ceylana** [comment]
@purvi-ranawat is this all good and can we close this issue?

**Comment by purvi-ranawat** [comment]
@tladesignz Arrow is missing which is required as mentioned in the link above.

Tested on iPhone XR iOS 17.2, App version 3.0.1, build 90

![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/7433e8e8-7e23-4139-a22d-b420807edff6)

**Comment by tladesignz** [comment]
We don't have that on Android, and I won't start with it on iOS now. Have no clue, how to implement that, trying it would cost a *serious* amount of money.
