### ISSUE TITLE
Create new colors scheme and template

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#248]
We should create a new colors scheme and template that we can use with the redesign.

dark grey from menus: #696666
gray: #9F9F9F;
teal: #00B4A6
background in dark mode: #000000

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment]
Was implicitly done when working on the other issues.
