### ISSUE TITLE
Implement new hamburger menu

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#249]
The new hamburger menu implements both a view for the current backend and all the configured backend.

![Home - Menu Dropbox](https://github.com/OpenArchive/Save-app-android/assets/1177650/d550fecf-5610-4cdd-8112-39bcd90212f1)

![Home - Menu](https://github.com/OpenArchive/Save-app-android/assets/1177650/662720b2-7d29-4a9c-a3f0-c22b01868241)

**Comment by tladesignz** [comment]
@purvi-ranawat: This will be contained in the upcoming TestFlight for version 3.0.0, build 80. Have to wait until version 2.9.0 is released (I totally forgot about that) until I can create that next TestFlight. Will take some days.

**Comment by purvi-ranawat** [comment]
@tladesignz It works fine on Version 3.0.0 (80)
