### ISSUE TITLE
Change "User Name" to "Username" on server login screens

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#250]
Change "User Name" to "Username" on server login screens - cultural spelling differences :)

Thanks!
![IMG_9047](https://github.com/OpenArchive/Save-app-ios/assets/2231711/0fa3d7dd-2e5d-4908-8995-bc6ec2c0c42f)

**Comment by tladesignz** [comment]
@purvi-ranawat, will be contained in version 3.0.0, build 81.

**Comment by purvi-ranawat** [comment]
@tladesignz,  It works fine on version 3.0.0 build 81. Tested on iPhone XR, iOS 17.2
