### ISSUE TITLE
"Data Usage" in App Settings smaller font than rest

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#251]
**Describe the bug**
"Data Usage" in App Settings smaller font than rest

**Expected behavior**
"Data Usage" should be the same font size as the other language on that page

**Screenshots**
![IMG_9063](https://github.com/OpenArchive/Save-app-ios/assets/2231711/33c627b9-0d52-4782-a871-ec888e1c8055)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 16.6.1

**Comment by tladesignz** [comment]
That is weird. But deprecated. The new designs are already implemented. This will change completely with version 3.
