### ISSUE TITLE
Missing Icon by Server Name if Not logged in to any Server 

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#253]
**Describe the bug**
Testing Save on ios and if you don't log in to the server there is no icon available by the server. We may need a generic icon. There are icons for Dropbox, IA and Nextcloud. 
![signal-2023-11-29-165244](https://github.com/OpenArchive/Save-app-ios/assets/145493085/cd3ce5ac-e652-4178-8a6b-21ee7e182e48)

**To Reproduce**
1. Download Save fresh without any servers set up
2. Click on hamburger menu
3. See error

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS817.1.1
 - Save version 3.0.0 85

**Comment by tladesignz** [comment]
Fixes will be contained in TestFlight version 3.0.1, build 87.

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the screenshot : 




![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/10fe0e70-85ac-4c28-8877-fabf83726b82)


Environment : 

OS : IOS 17.2
Device : iphone XR
Build Version : 3.0.0.build 87
