### ISSUE TITLE
About Save link on Settings Screen Going to Wrong Webpage

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#254]
**Describe the bug**
About Save link is linking to the 'about us' page on our website but should be linking to open-archive.org/save

**To Reproduce**
1. Go to Settings
2. Click on about Save
3. See error

**Expected behavior**
Needs to direct to: open-archive.org/save

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.0 85

**Comment by tladesignz** [comment]
Fix will be contained in TestFlight version 3.0.1, build 87.

**Comment by purvi-ranawat** [comment]
This is working fine. Tested on iPhone XR iOS 17.2 app version 3.0.1, build 87
