### ISSUE TITLE
Font Size for Links on Settings Screen Too Big

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#255]
**Describe the bug**
font size for 'about save' and 'privacy policy' should be a smaller font size than the general, dropbox, and folder sections on settings. 

**To Reproduce**
1. Go to Settings
3. See error

**Screenshots**
If applicable, add screenshots to help exp
![signal-2023-11-29-165244](https://github.com/OpenArchive/Save-app-ios/assets/145493085/a82229df-f2bc-4334-9e0a-51e3efbb68b4)
lain your problem.

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.0 85

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/bedb67bc-6791-4d43-9052-ab71a4b87d55)


Environment : 

OS : IOS 17.2
Device : iphone XR
Build version : 3.0.0.build 87
