### ISSUE TITLE
Significant Content Flag is Not Turning Yellow 

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#256]
**Describe the bug**
When uploading media and selecting the significant content flag, it is not turning yellow

**To Reproduce**
1. Go to plus icon
2. Click on photo to upload and edit metadata/select significant content flag

**Expected behavior**
Flag turns yellow

**Screenshots**

![significant content flag](https://github.com/OpenArchive/Save-app-ios/assets/145493085/646b7e9c-ce8b-40ed-9819-44a3939c6801)

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.0 85

**Comment by tladesignz** [comment]
Fix will be contained in TestFlight version 3.0.1, build 87.

**Comment by purvi-ranawat** [comment]
@tladesignz  : Background of Significant content flag icon is also turning yellow along with the flag color which looks wierd.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/8cd5096f-9039-4a33-9fc4-096231ea2182)


Environment : 

OS : IOS 17.2
Device : Iphone XR
Build version : 3.0.0.build 87

**Comment by tladesignz** [comment]
@purvi-ranawat, fix will be contained in version 3.0.1, build 89.

**Comment by purvi-ranawat** [comment]
@tladesignz This is working fine now. Tested on iPhone XR, iOS 17.2, app version 3.0.1, build 89
