### ISSUE TITLE
Delete Media from App Icon Too Close to Hamburger Menu

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#258]
**Describe the bug**

**To Reproduce**
Select an uploaded media and see the trash icon at the top right
![trashicon](https://github.com/OpenArchive/Save-app-ios/assets/145493085/8046a449-4691-40f9-a1ea-b648720cca5c)

**Expected behavior**
It would be nice for there to be more space between trash and hamburger folder so people don't accidentally press the wrong thing. 

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Save version 3.0.0 85

**Comment by losalim** [comment]
Editing to add Natalie's comment: After selecting an uploaded image from gallery view, the trash can is too close to the hamburger should go to the right under the number of uploaded images on the right

**Comment by tladesignz** [comment]
Yeah, well, that was the easy thing to do, but then I read [this](https://github.com/OpenArchive/Save-app-ios/issues/258#issuecomment-1836560739), so I came up with the other solution.

A new fix will be contained in version 3.0.1, build 88.

**Comment by ceylana** [comment]
looks like this is resolved as Lauren tested 3.0.1 build 87. Okay to close?

**Comment by purvi-ranawat** [comment]
@tladesignz / @ceylana : I was waiting for build 88 but this is working fine in build 87. Now delete media icon is below the hamburger Menu. 

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/057e946f-131c-4d72-9e98-95f2248c062b)


Environment : 

OS : IOS 17.2
Device : Iphone XR
Build Version : 3.0.1.build 87

**Comment by tladesignz** [comment]
> @tladesignz / @ceylana : I was waiting for build 88 but this is working fine in build 87. Now delete media icon is below the hamburger Menu.

Yeah, I changed that again after further conversation. Please check build 88.

**Comment by ceylana** [comment]
Closing this issue since it is resolved!!!!
