### ISSUE TITLE
Uploaded numbers formatting change requested : can we round the boxes, make them teal with white or black numbers (depending on light/dark mode) 

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#260]
**Describe the bug**
Can we edit the number boxes on the right on the my media screen ? changes would include making the grey boxes rounded and teal, and the characters white or black. 

**To Reproduce**
1. Go to my media screen
2. See error

**Expected behavior**
boxes with number of uploads should be formatted with rounded boxes. Can we make these boxes teal? And have white or black characters depending on light/darkmode?

**Screenshots**
Adding screenshot of ios app right now 
![iosDec4](https://github.com/OpenArchive/Save-app-ios/assets/145493085/71a5550a-f26e-456b-84b9-2f902a4bf7c0)

**Smartphone (please complete the following information):**
 - Device: [iphone 12 mini
 - OS: [e.g. 17.1.1
 - Version 3.0.0 build 86

**Comment by tladesignz** [comment]
Fix will be contained in version 3.0.1, build 88.

**Comment by ceylana** [comment]
@tladesignz  confirming that the numbers are now in the rounded grey boxes. 

Referenced the designs in figma for the colors to be used for accessibility purposes.
**For dark mode:**  please change the grey circle to HEX color # 434343 (number should be white). 
**for light mode:** please make sure the grey circle is HEX color #E3E3E4 (number should be black).

thanks!

**Comment by tladesignz** [comment]
As you wish...

Will be contained in version 3.0.1, build 91.

**Comment by losalim** [comment]
Tested in build 91. Issue resolved
