### ISSUE TITLE
iOS app crashed when removing folder from app

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#261]
**Describe the bug**
app crashed when deleting a folder from the app. reproduced 3 times

**To Reproduce**
1. Go to settings
2. Click on folder
3. Change or Delete Folder

**Screenshots**

https://github.com/OpenArchive/Save-app-ios/assets/145493085/ec59d663-cf28-4047-82a7-0766698ccdf4

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.1. build 89

**Comment by losalim** [comment]
@purvi-ranawat can you test this as well?

**Comment by tladesignz** [comment]
@losalim, thanks for catching this!

A fix will be contained in version 3.0.1, build 90.

**Comment by losalim** [comment]
All fixed on my end thank you @tladesignz
