### ISSUE TITLE
Creative Commons Licensing - Not all options available

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#262]
**Describe the bug**
Right now CC licensing is just on/off for folder or all folders on server. i think we are supposed to have more options including commercial use, remixing, etc. 

<img width="1176" alt="Screenshot 2023-12-11 at 14 22 23" src="https://github.com/OpenArchive/Save-app-ios/assets/145493085/dac2d410-93f4-4ef7-8f87-51be90a00291">
![CC1](https://github.com/OpenArchive/Save-app-ios/assets/145493085/a3999a1f-c490-4b34-9d3f-7f3d0a16dcd4)
![cc2](https://github.com/OpenArchive/Save-app-ios/assets/145493085/64fa6b2f-bda9-47ae-b802-c03803ceb0c7)

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.1 build 89

**Comment by losalim** [comment]
![CC1](https://github.com/OpenArchive/Save-app-ios/assets/145493085/b7f4260d-84de-4e3c-a396-bc46f0a07b36)
![cc2](https://github.com/OpenArchive/Save-app-ios/assets/145493085/6798c05b-f542-4291-9e66-5c3ba9919efc)

**Comment by tladesignz** [comment]
Please toggle switch, you will see options then.
