### ISSUE TITLE
Server icons should all be white (in dark mode) or black (in light mode)

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#264]
**Describe the bug**
Right now server icons are the default branding of the server but  we wanted them all black or all white in the figma designs. 

![server icons](https://github.com/OpenArchive/Save-app-ios/assets/145493085/59168a99-f40d-4f38-b8e2-19a53fcc808f)

Version 3.0.1. Build 90

**Comment by tladesignz** [comment]
Will be fixed in version 3.0.1, build 91.

**Comment by purvi-ranawat** [comment]
@tladesignz : Server icons and the icons on the Settings screen are not all white when on the black background as mentioned in the figma designs

Below are the screenshots : 

Actual screen : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/9ed9ddb7-48fd-4900-a232-6c7a6f5f3d5d)

Requirement Screen : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/e835862e-d973-4624-8542-f18a0bfb25be)


Environment : 
OS : IOS 17.2
Device : Iphone XR
Build Version : 3.0.1, build 91

**Comment by tladesignz** [comment]
@purvi-ranawat, I won't try to colorize custom icons acquired from WebDAV servers. That would most probably just lead to black / white blobs.

However, I did realize that the buttons in the settings scene where green for an unknown reason. I changed it to black/white.

Thank you very much for your diligence!

Change will be contained in build 92.

**Comment by purvi-ranawat** [comment]
@tladesignz  This is resolved now. Tested on iPhone XR OS version 17.2, app version 3.1.0 build 92.
