### ISSUE TITLE
Grey Circle Around Server Icon on Server Connection is Hard to See

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#266]
**Describe the bug**
When you sign in to any of the servers, the icon is set within a grey box that is difficult to see. I think in the figma designs it is darker so the icon stands out 

build 91
![image](https://github.com/OpenArchive/Save-app-ios/assets/145493085/ffab8247-0ffc-4e3b-b1ec-c7606c4f9fed)

iphone 12 mini, 17.1.1

**Comment by tladesignz** [comment]
Will be contained in build 92.

**Comment by purvi-ranawat** [comment]
@tladesignz  This is resolved now. Tested on iPhone XR OS version 17.2, app version 3.1.0 build 92.
