### ISSUE TITLE
Successfully Connected to Server Screen is in the middle of the screen - doesn't match figma

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#267]
The screen you get when you've successfully connected to any server is sort of centered within the screen. in the figma designes, done is at the bottom at the graphic takes up more of the screen. 

![image](https://github.com/OpenArchive/Save-app-ios/assets/145493085/7aedd7e4-c58b-4820-8850-f74c099d1f42)

Build 91, iphone 12 mini, ios 17.1.1

**Comment by tladesignz** [comment]
Will be contained in build 92.

**Comment by purvi-ranawat** [comment]
@tladesignz This is working fine. Tested on iPhone XR, OS version 17.2. App version 3.1.0, build 93.
