### ISSUE TITLE
Creative Commons Licensing - Not prompting you to add it when creating new folder

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#268]
**Describe the bug**
When you. create a new folder in the app for android i believe we built in creative commons settings when you're naming the folder. I don't believe this is present in the iOS version yet. 

**To Reproduce**
1. Go to teal plus
2. Click on create new folder
3. See error

**Expected behavior**
Prompts you to set CC licensing when creating a new folder. 

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version build 91

**Comment by tladesignz** [comment]
Will be contained in build 92!

**Comment by purvi-ranawat** [comment]
@tladesignz It works fine now.  Tested on iPhone XR iOS version 17.2, app version 3.1.0, build 93.
