### ISSUE TITLE
Missing pop-up letting first time users know to long hold + sign for other files

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-ios#269]
**Description
The pop-up letting first-time users know to long hold + sign to select between the gallery and other files/media is missing. This should appear once a folder has been added an users are able to add media.

**Screenshots**
![image](https://github.com/OpenArchive/Save-app-android/assets/37166640/1c10941e-7fd3-4095-875a-f1381a5407f1) This is the popup that should be there

**Comment by tladesignz** [comment]
If we would make better use of the bottom bar, we wouldn't need to annoy the user with instructions. A UI should explain itself.

Anyway, I added it, albeit with slightly changed wording. I mean "non-camera apps"? WTF?


Will be contained in build 93.

**Comment by purvi-ranawat** [comment]
@tladesignz Pop up is getting displayed now. Tested on iPhone XR iOS version 17.2, app version 3.1.0, build 93.
