### ISSUE TITLE
Internet archive : Entering random characters in secret keys for internet archive does not give any error message

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#270]
Bug Description : 

While adding the internet archive server, if instead of entering the valid access key or click on acquire keys, if we enter random characters and click on Next, Internet Archive server is added. Instead it should give the error message stating to enter valid access key.

1. Go to Save App.
2. Click on Internet Archive to add Internet Archive server
3. Enter random characters in Access keys fields and click on Next

Expected behavior : 
Error message should be display stating to enter valid Access Keys

Actual behaviour : 
No error message is displayed on entering the wrong access keys and internet archive server is added.

Below is the video : 

https://github.com/OpenArchive/Save-app-ios/assets/8190141/eb4161b2-dbd6-4024-b747-0ab0f9b69931

**Desktop (please complete the following information):**
   OS: IOS 17.2
Device : Iphone XR
 - Version : 3.0.0,build 93

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tladesignz** [comment]
So, I just researched this again. Unfortunately, it is not possible to reliably test, if the keys are valid. Hence the iOS app did never try to.

The main problem is, that requests to the Internet Archive S3 root with valid credentials from new accounts look exactly the same as answers to invalid credentials.

This is related to https://github.com/OpenArchive/Save-app-android/issues/496.
