### ISSUE TITLE
Friction with toggling Lock app off after disabling proofmode

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#271]
**Describe the bug**
One should be able to toggle the "Lock App with Face ID or Device Passcode" after disabling Proofmode. Unfortunately one must close the app after disabling proofmode in order to turn off the Lock App feature. We not only need to fix this bug, but to create documentation/informational popup explaining how this works (and why).

**To Reproduce**
1. Go to Settings / General
2. Click on ProofMode
3. Deselect "Enable ProofMode" and deseclt "Secure ProofMode Key with Face ID or Device Passcode"
4. Go back to General Settings and try to deselect Lock App with Face ID or Device Passcode - you can't.
5. Close and reopen app, now you can deselect Lock App....

**Expected behavior**
One should not have to close the app after disabling proofmode in order to turn off the Lock App feature, it should automatically become a functional button vs. grayed out.

**Screenshots**
![signal-2024-01-08-123455_003](https://github.com/OpenArchive/Save-app-ios/assets/2231711/af4685e0-6479-4525-bd78-0eca665ef62e)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: 17.1.2
 - Version 3.1.0 build 93

**Additional Notes**
We need to make sure this is working on Android

**Comment by tladesignz** [comment]
This was broken because the settings form was torn apart in two pieces during the redesign, and the dependency between "app-lock" and "secure-proofmode-key" was lost.

I fixed it and also added an explanatory text to when "app-lock" is unchangeable because a ProofMode key is secured.

This will be contained in build 96.

**Comment by foundscapes** [comment]
This is fixed in build 97 but there are spacing issues with the new language you added for clarity (ty for that!). Please fix and we can close!
![signal-2024-01-10-114724](https://github.com/OpenArchive/Save-app-ios/assets/2231711/2275714e-a70a-4bd8-a59b-a185fe12c572)

**Comment by tladesignz** [comment]
#%&!*...

Fix will be contained in build 98.

**Comment by foundscapes** [comment]
@tladesignz this is fixed, but now all the teal headings are cropped for both me and Lauren (iphone 12 minis)
![IMG_0664](https://github.com/OpenArchive/Save-app-ios/assets/2231711/db33defc-fbbe-4471-86e6-5d24c8f9cc86)

**Comment by tladesignz** [comment]
Might be fixed in build 99.

**Comment by purvi-ranawat** [comment]
This is working fine.

Environment Details : 

OS : IOS 17.2
Device : Iphone XR
Build Version : 3.0.0, build 100

**Comment by foundscapes** [comment]
The teal headers are still cut off for me in build 100 
![IMG_0704](https://github.com/OpenArchive/Save-app-ios/assets/2231711/12709543-ae98-4ce2-9d00-0bae895fd6ba)

**Comment by tladesignz** [comment]
*sigh*

Should be fixed in build 101.

**Comment by purvi-ranawat** [comment]
This is working fine.

Environment Details : 
OS : IOS 17.2
Device : Iphone XR
Build Version : 3.0.0, build 101
