### ISSUE TITLE
Hide App Content when in Background Feature Not Working

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#272]
**Describe the bug**
When I have that feature turned on, the app content isn't hidden in the background (I believe it shows the first welcome screen, not whatever screen you were actually on), which is maybe not helpful because it will alert authorities to what the app will do. 

**Expected behavior**
I think we wanted that feature to black out or blurr app contents when in the background

**To Reproduce**
Turn on hide app contents in background feature
Put app in background

**Screenshots**
![signal-2024-01-16-133135_002](https://github.com/OpenArchive/Save-app-ios/assets/145493085/c40b5eb3-6245-4aa4-baf1-0638ef9b1006)
![signal-2024-01-16-133020_002](https://github.com/OpenArchive/Save-app-ios/assets/145493085/fb86d75a-e2dd-4d92-b507-71fb3831d5f9)

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.2.1
 - Version testflight 3.1.1 build 99

**Comment by purvi-ranawat** [comment]
@tladesignz This is working fine. 
Tested on iPhone XR 17.2. App version 3.1.1, build 100
