### ISSUE TITLE
GDrive Policy View is Hidden

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#273]
**Describe the bug**
When you go to authenticate GDrive the policy goes behind the link and is hard to see. 
![gdrive policy](https://github.com/OpenArchive/Save-app-ios/assets/145493085/96cd637d-394d-40cf-a79f-8fe49a4effcb)

Maybe make the overlay lighter so people can read it? or just move it above

Smartphone
 - OS: 17.2
 - Device: 12 mini iphone
 - Version 3.2.0 build 107

**Comment by tladesignz** [comment]
Upsi. Dark mode.

**Comment by tladesignz** [comment]
Fix will be contained in build 108 and newer.

**Comment by foundscapes** [comment]
The link to the data policy should definitely be moved above the background text and under "Sign in with Google"

**Comment by tladesignz** [comment]
Confused because of the black-out? This text (incl. the link) was handed down by the Google gods. No changies.

The only problem here is that the text is black-on-black when in dark mode. That was fixed.

**Comment by foundscapes** [comment]
@tladesignz that link should not be placed where it is, it needs to be moved above the background policy text.

**Comment by purvi-ranawat** [comment]
@tladesignz / @foundscapes : This is working fine on iphone XR

Below is the screenshot : 

![image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/97c8413b-39c0-4807-a407-cb7cc22ea777)

Environment : 
OS : IOS 17.4
Device : Iphone XR
Build : 3.2.1 build 109
