### ISSUE TITLE
Code vs. Plain error language

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#276]
**Describe the bug**
When upload doesn't work, we get incomprehensible error - this happened when connected/uploading to DropBox 

**To Reproduce**
1. Add media
2. Upload media
3. See weird error

**Expected behavior**
Errors should all be in plain language.

**Screenshots**
![IMG_1038](https://github.com/OpenArchive/Save-app-ios/assets/2231711/6504d58e-1477-481a-92b5-150ca56c40e9)

**Smartphone (please complete the following information):**

**Comment by tladesignz** [comment]
The important information here seems to have been the piece `insufficient_space´.
I could reproduce that error by filling up my Dropbox to the brim.

I tried to improve the output of error messages from Dropbox. (See the commit link above for some crazy code I had to write to achieve this.)

I am  not (and nobody else is), and never will be able to produce human-friendly error messages for all circumstances. There's tons of layers of code and systems that can produce all sorts of different errors in all sorts of crazy data structures.

The only thing we could do generally is to say "There was some error." That is human-readable, but it also contains zero information to *what* actually went wrong.

However, for many people, even a really ugly error message can help them fix their problem. Like in this case, those who bothered to try to spot some interesting information in there could come to the conclusion, that they maybe would need to clean up their Dropbox to continue working with it.

But I am happy to dissect any wild error you stumble across and make that nicer, as long as I am able to reproduce it.

Like in this case.

I think we discussed this already somewhere, but I can't find that issue now. Anyhow.

The fix will be contained in build 109.

**Comment by tladesignz** [comment]
@purvi-ranawat, you can test this error by filling up your Dropbox to the max!

**Comment by purvi-ranawat** [comment]
@tladesignz : This is working fine. I am getting only Insufficient_space message.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/55808219-c34a-4e62-882f-69a0dc8b8912)


Environment : 
OS : IOS 17.2
Device : Iphone XR
Build Version : 3.2.1, build 109
