### ISSUE TITLE
Arrow pointing towards + sign for adding media not implemented. 

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-ios#278]
**Describe the bug**
Arrow pointing towards + sign for adding media not implemented. 

**To Reproduce**
1. Go to Save app
2. Add folder via Dropbox or any other server
3. The main screen for adding the media doesn't have the arrow as intended in design here: https://www.figma.com/file/Im6CrTczfYYDTLS6LdRTk0/Save-App-2.0?type=design&node-id=432-2617&mode=design&t=CDNdTMHrJPm0oPYv-0#726591270

**Expected behavior**
The arrow animation should be implemented 

**Screenshots**
![1 3 Home - First time user](https://github.com/OpenArchive/Save-app-android/assets/64951124/8ef02897-4217-4da2-a092-bc3ef01c4e3b)

**Comment by tladesignz** [comment]
That'll probably eat a lot of hours compared to the seemingly pretty minor gain in usability. (No idea, really but probably somewhere between 8 - 16? NO guarantees, though.)
@foundscapes, is that ok with you? Maybe you want to set a limit on how much to spend?

**Comment by tladesignz** [comment]
Or @ceylana, maybe you want to take this responsibility, in case @foundscapes is head-over-heels in other things?
