### ISSUE TITLE
Update language for adding new folder for first time user

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-ios#280]
**Describe the bug**
The current language needs to be updated as per the Figma design

**Expected behavior**
The language should be as suggested here:
![1 0 Home - First time user no project](https://github.com/OpenArchive/Save-app-ios/assets/64951124/cf12550a-bce6-4a17-a681-87bc6c0d976a)

**Comment by tladesignz** [comment]
Please provide access to Figma file. I sent a request.

**Comment by tladesignz** [comment]
AFAIU, these are the requested changes:

- Change alert title from "To get started, please create a folder" into "To get started, please add a folder"
- Remove alert body: "Before adding media, create a new folder first."

**Comment by tladesignz** [comment]
@vanichitkara, @purvi-ranawat: Fix will be contained in version 3.3.0, build 112, available on TestFlight later today.

**Comment by tladesignz** [comment]
For context: It's about the folder alert which shows up, the first time you try to add an asset without having added a folder to a space, yet.

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/02e7fc38-8d7a-40cc-8cf2-bf8e0540ebcf)

Environment : 

OS : IOS 17.4
Device : Iphone XR
Build Version : 3.3.0 build 115
