### ISSUE TITLE
The folder icon in Android has teal outlined folder instead of teal filled folder icon as suggested in the Figma design

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-ios#282]
**Describe the bug**
Currently, the folder icon in Android has a teal-outlined icon, which is different from the Figma design. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new server
2. Add some folder 
3. Click on the top right hamburger menu
4. You'll see the list of folders with the teal-outlined folder icon

**Exbehaviourehavior**
The folder icon should be teal-filled, as the Figma design suggests.

**Screenshots**
![Screenshot_2024-03-10-16-47-22-72_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/3f689ffd-5773-42f1-ac33-a80059fcd54d)

**Comment by tladesignz** [comment]
@vanichitkara, this is for Android, right? Can you please move/recreate this issue over there?
https://github.com/OpenArchive/Save-app-android/issues/

Thank you!

**Comment by tladesignz** [comment]
I see, there's an issue for Android: https://github.com/OpenArchive/Save-app-android/issues/584

Since iOS isn't affected by this, I'll close this issue.
