### ISSUE TITLE
New Hamburger implementation for servers

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-ios#283]
Implementation of a new hamburger menu for the servers.

The new design:
![1 4c Home - Media - Private Server signed in](https://github.com/OpenArchive/Save-app-ios/assets/64951124/a7f46a89-4a0f-4f56-98e1-e838482bc6e0)
![1 4d Home - Menu](https://github.com/OpenArchive/Save-app-ios/assets/64951124/a4d54a79-bb0c-40ef-9ca0-6f7e8a43ffcd)

**Comment by tladesignz** [comment]
Ah, ok. Now I get it.

For the future: Please don't just edit the issue. I won't get a notification about it. If instead of commentiing, an edit of the original issue seems more appropriate, please also leave a short comment that you did that, so I will be informed, that something changed.

Thanks!

**Comment by tladesignz** [comment]
Will be contained in version 3.3.0, build 115!

**Comment by foundscapes** [comment]
@vanichitkara please test, it's working great for me!

**Comment by vanichitkara** [comment]
This is working great for me too!
OS: iOS 16.7.7
Device: iPhone 8 Plus
Version: 3.3.0, build 117
