### ISSUE TITLE
Add built-in Tor

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-ios#284]
Since Orbot faces tough times and became unstable and had bridge support removed due to absurd memory constraints by Apple, we finally want our own built-in Tor.

**Comment by tladesignz** [comment]
This will be contained in version 3.3.0, build 113 via TestFlight!

**Comment by foundscapes** [comment]
@vanichitkara please test

**Comment by foundscapes** [comment]
We decided on our call to deprecate/remove Orbot from Save, which involves:

1. @tladesignz to remove the toggle from settings
2. @tladesignz  removing the download link from the onboarding screen and updating the language to: Automatically upload over TLS (Transport Layer Security) and enable Tor (The Onion Router) in-app to protect your media in transit. 
Enable "Transfer via Tor only" for advanced network security. [[then that automatically switches this setting on in settings?]] If not, we can remove that part or change it to: Enable "Transfer via Tor only" in settings after on-boarding.
3. updating the language in settings to read: Transfer via Tor only [explainer text below] Enable Tor to protect your media in transit.

**Comment by tladesignz** [comment]
Requested change will be contained in version 3.3.0, build 116.

**Comment by vanichitkara** [comment]
This is working great for me!
OS: iOS 16.7.7
Device: iPhone 8 Plus
Version: 3.3.0, build 117
