### ISSUE TITLE
 keyboard overlaps functions/indicators

### ISSUE THREAD

**Issue by ryjen** [OpenArchive/Save-app-ios#302]
**Describe the bug**

Adding a new webdav server assumes appending '/remote.php/webdav' to url?

keyboard hides fields, with no 'next' action instead of 'return'

was attempting a 4shared account instead of nextcloud

**To Reproduce**
1. Click '+'
2. Add server
3. add https://webdav.4shared.com/
4. add user/pass
5. See error

**Expected behavior**
Able to login, url does not change, can navigate fields from keyboard overlay

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by foundscapes** [comment]
Keyboard overlaps pw screen when logging into nextcloud and obscures chunking option

**Comment by foundscapes** [comment]
> **Describe the bug**
> 
> Adding a new webdav server assumes appending '/remote.php/webdav' to url?
@ryjen this is expected behavior

> 
> keyboard hides fields, with no 'next' action instead of 'return'
> 
> was attempting a 4shared account instead of nextcloud
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Click '+'
> 
>     2. Add server
> 
>     3. add https://webdav.4shared.com/
> 
>     4. add user/pass
> 
>     5. See error
> 
> 
> **Expected behavior** Able to login, url does not change, can navigate fields from keyboard overlay
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. iOS]
> 
>     * Browser [e.g. chrome, safari]
> 
>     * Version [e.g. 22]
> 
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: [e.g. iPhone6]
> 
>     * OS: [e.g. iOS8.1]
> 
>     * Browser [e.g. stock browser, safari]
> 
>     * Version [e.g. 22]
> 
> 
> **Additional context** Add any other context about the problem here.

**Comment by foundscapes** [comment]
v. 3.4.0 build 143 --> keyboard is movable now, but still obscures "next" button when trying to connect to server

**Comment by rapuckett** [comment]
<img width="391" alt="image" src="https://github.com/user-attachments/assets/61d0bba8-37c5-444c-acb4-6c01e9e4f221">

ec06c68
