### ISSUE TITLE
Add padding to bottom bar icons

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#303]
images updated in build 44 but needs more padding between bottom and images and text and images

![Image](https://github.com/user-attachments/assets/47fa0e88-4f4d-4db8-bc24-a15c0d83474d)

OG files
![Image](https://github.com/user-attachments/assets/720122c6-6b0b-48ca-911d-542359b89e50) update this to this:
![Image](https://github.com/user-attachments/assets/2e1589c1-248a-4ee2-93bc-26d22dd83b33)

**Comment by rapuckett** [comment]
<img width="420" alt="image" src="https://github.com/user-attachments/assets/06f4dc77-1178-4692-b8e5-72704b196dd3">
