### ISSUE TITLE
Missing arrow and/or plus sign before “button”

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#304]
![Image](https://github.com/user-attachments/assets/ceed5a11-6838-477f-b270-97fb6b0d06af)

**Comment by rapuckett** [comment]
<img width="282" alt="image" src="https://github.com/user-attachments/assets/28505376-d6db-431d-aaef-bece164541ec">

4b451e68d2de8a54c2a4194ccf531c3cb1c00621
