### ISSUE TITLE
Add notes/ location  too close to bottom needs padding / to be higher

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#306]
![Image](https://github.com/user-attachments/assets/e9b9071f-eb9e-4648-afe5-d4e0d548dcf1)

**Comment by purvi-ranawat** [comment]
The issue exists in version 3.4.0, build 144. Tested on iPhone 15, iOS 17.7.1

**Comment by rapuckett** [comment]
Resolved in [4f65a6d](https://github.com/OpenArchive/Save-app-ios/commit/4f65a6d11f2bf9d8acbdfc1afef922780ea6e42b)
