### ISSUE TITLE
Support password managers to support credential distribution

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-ios#43]
LastPass support would be great, for enterprise credential distribution among organizations

**Comment by foundscapes** [comment]
resolved!

**Comment by tladesignz** [comment]
Just for info, if this ever comes up again: LastPass went bad. They were bought up by some investment firm. They had a serious security incident. They way how that came to be and how they behaved in the aftermath makes them now the last choice on earth for password handling.

You can read more here (and of course tons of other sources): https://www.forbes.com/sites/daveywinder/2023/03/03/why-you-should-stop-using-lastpass-after-new-hack-method-update/

**Comment by foundscapes** [comment]
@tladesignz we know - we don't use LastPass.
