### ISSUE TITLE
Integrate AirDrop so people can share locally on iOS

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#92]

**Comment by tladesignz** [comment]
They already can share media using the respective apps like the "Photos" app or the voice recorder app. Why should they use OpenArchive for that?

What else should they want to share? The metadata? The server configs? That would only be useful in another instance of iOS OpenArchive. To share the assets, the sorting of them and their metadata would be quite some work. The server configs less so, but compared to the benefit...

**Comment by foundscapes** [comment]
But what about use cases when they also want to share proofmode data? Would that be a lot of work?

**Comment by n8fr8** [comment]
We need to have a longer discussion about this feature. Let's not start back and forth yet on this ticket.

**Comment by foundscapes** [comment]
Discuss share between android and iphone in future
